//! Project trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::Project;

pub type ProjectTriggerEvent      = TriggerEvent;
pub type ProjectTriggerContext    = TriggerContext<Project>;
pub type ProjectTriggerContextMut = TriggerContextMut<Project>;
pub type ProjectActionExecutor    = ActionExecutor;
pub type ProjectTriggerRegistry   = TriggerRegistry<Project>;
pub type ProjectTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<Project>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for Project.
pub fn project_trigger_registry() -> ProjectTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
