//! Bulk operations for ProjectTemplateTask entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateProjectTemplateTaskDto;
use crate::application::service::ProjectTemplateTaskService;
use crate::domain::entity::ProjectTemplateTask;

/// Bulk operation handler for ProjectTemplateTask entities.
///
/// Wraps `ProjectTemplateTaskService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ProjectTemplateTaskBulkService = GenericBulkService<ProjectTemplateTask, CreateProjectTemplateTaskDto, ProjectTemplateTaskService>;

// <<< CUSTOM
// END CUSTOM
