//! Bulk operations for ProjectTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateProjectTemplateDto;
use crate::application::service::ProjectTemplateService;
use crate::domain::entity::ProjectTemplate;

/// Bulk operation handler for ProjectTemplate entities.
///
/// Wraps `ProjectTemplateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ProjectTemplateBulkService = GenericBulkService<ProjectTemplate, CreateProjectTemplateDto, ProjectTemplateService>;

// <<< CUSTOM
// END CUSTOM
