//! Bulk operations for Project entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateProjectDto;
use crate::application::service::ProjectService;
use crate::domain::entity::Project;

/// Bulk operation handler for Project entities.
///
/// Wraps `ProjectService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ProjectBulkService = GenericBulkService<Project, CreateProjectDto, ProjectService>;

// <<< CUSTOM
// END CUSTOM
