//! Bulk operations for Task entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTaskDto;
use crate::application::service::TaskService;
use crate::domain::entity::Task;

/// Bulk operation handler for Task entities.
///
/// Wraps `TaskService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TaskBulkService = GenericBulkService<Task, CreateTaskDto, TaskService>;

// <<< CUSTOM
// END CUSTOM
