//! Bulk operations for TimesheetDetail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimesheetDetailDto;
use crate::application::service::TimesheetDetailService;
use crate::domain::entity::TimesheetDetail;

/// Bulk operation handler for TimesheetDetail entities.
///
/// Wraps `TimesheetDetailService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimesheetDetailBulkService = GenericBulkService<TimesheetDetail, CreateTimesheetDetailDto, TimesheetDetailService>;

// <<< CUSTOM
// END CUSTOM
