//! ProjectTemplate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ProjectTemplate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ProjectType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ProjectTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProjectTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "template_name")]
    pub template_name: String,
    #[serde(alias = "project_type")]
    pub project_type: ProjectType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ProjectTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProjectTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "template_name")]
    pub template_name: String,
    #[serde(alias = "project_type")]
    pub project_type: ProjectType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ProjectTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProjectTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_name")]
    pub template_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "project_type")]
    pub project_type: Option<ProjectType>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchProjectTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.template_name.is_some() || self.project_type.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ProjectTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub template_name: String,
    pub project_type: ProjectType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ProjectTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateListResponseDto {
    /// List of items
    pub items: Vec<ProjectTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProjectTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProjectTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_name: String,
    pub project_type: ProjectType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ProjectTemplate> for ProjectTemplateResponseDto {
    fn from(entity: ProjectTemplate) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_name: entity.template_name,
            project_type: entity.project_type,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<ProjectTemplate> for ProjectTemplateSummaryDto {
    fn from(entity: ProjectTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_name: entity.template_name,
            project_type: entity.project_type,
            created_at,
        }
    }
}

impl From<CreateProjectTemplateDto> for ProjectTemplate {
    fn from(dto: CreateProjectTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            template_name: dto.template_name,
            project_type: dto.project_type,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ProjectTemplate> for ProjectTemplateResponseDto {
    fn from(entity: &ProjectTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            template_name: entity.template_name.clone(),
            project_type: entity.project_type.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProjectTemplateDto> for ProjectTemplate {
    fn from_create_dto(dto: CreateProjectTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(ProjectTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProjectTemplateDto> for ProjectTemplate {
    fn apply_update(mut self, dto: UpdateProjectTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.template_name = dto.template_name;
        self.project_type = dto.project_type;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ProjectTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

