//! Project DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Project;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ProjectStatus;
use crate::domain::entity::ProjectType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Project
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProjectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "project_name")]
    pub project_name: String,
    #[serde(alias = "project_type")]
    pub project_type: ProjectType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_so_id")]
    pub source_so_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: ProjectStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_start_date")]
    pub expected_start_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_end_date")]
    pub expected_end_date: Option<DateTime<Utc>>,
    #[serde(alias = "total_costing_amount")]
    pub total_costing_amount: Decimal,
    #[serde(alias = "total_billable_amount")]
    pub total_billable_amount: Decimal,
    #[serde(alias = "total_billed_amount")]
    pub total_billed_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Project
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProjectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "project_name")]
    pub project_name: String,
    #[serde(alias = "project_type")]
    pub project_type: ProjectType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_so_id")]
    pub source_so_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: ProjectStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_start_date")]
    pub expected_start_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expected_end_date")]
    pub expected_end_date: Option<DateTime<Utc>>,
    #[serde(alias = "total_costing_amount")]
    pub total_costing_amount: Decimal,
    #[serde(alias = "total_billable_amount")]
    pub total_billable_amount: Decimal,
    #[serde(alias = "total_billed_amount")]
    pub total_billed_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Project
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProjectDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "project_name")]
    pub project_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "project_type")]
    pub project_type: Option<ProjectType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_so_id")]
    pub source_so_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ProjectStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_start_date")]
    pub expected_start_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_end_date")]
    pub expected_end_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_costing_amount")]
    pub total_costing_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_billable_amount")]
    pub total_billable_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_billed_amount")]
    pub total_billed_amount: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchProjectDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.project_name.is_some() || self.project_type.is_some() || self.customer_id.is_some() || self.source_so_id.is_some() || self.currency.is_some() || self.status.is_some() || self.expected_start_date.is_some() || self.expected_end_date.is_some() || self.total_costing_amount.is_some() || self.total_billable_amount.is_some() || self.total_billed_amount.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Project entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub project_name: String,
    pub project_type: ProjectType,
    pub customer_id: Option<Uuid>,
    pub source_so_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub status: ProjectStatus,
    pub expected_start_date: Option<DateTime<Utc>>,
    pub expected_end_date: Option<DateTime<Utc>>,
    pub total_costing_amount: Decimal,
    pub total_billable_amount: Decimal,
    pub total_billed_amount: Decimal,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Project entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectListResponseDto {
    /// List of items
    pub items: Vec<ProjectResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProjectListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProjectResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_name: String,
    pub project_type: ProjectType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Project> for ProjectResponseDto {
    fn from(entity: Project) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            project_name: entity.project_name,
            project_type: entity.project_type,
            customer_id: entity.customer_id,
            source_so_id: entity.source_so_id,
            currency: entity.currency,
            status: entity.status,
            expected_start_date: entity.expected_start_date,
            expected_end_date: entity.expected_end_date,
            total_costing_amount: entity.total_costing_amount,
            total_billable_amount: entity.total_billable_amount,
            total_billed_amount: entity.total_billed_amount,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<Project> for ProjectSummaryDto {
    fn from(entity: Project) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            project_name: entity.project_name,
            project_type: entity.project_type,
            created_at,
        }
    }
}

impl From<CreateProjectDto> for Project {
    fn from(dto: CreateProjectDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            project_name: dto.project_name,
            project_type: dto.project_type,
            customer_id: dto.customer_id,
            source_so_id: dto.source_so_id,
            currency: dto.currency,
            status: dto.status,
            expected_start_date: dto.expected_start_date,
            expected_end_date: dto.expected_end_date,
            total_costing_amount: dto.total_costing_amount,
            total_billable_amount: dto.total_billable_amount,
            total_billed_amount: dto.total_billed_amount,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Project> for ProjectResponseDto {
    fn from(entity: &Project) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            project_name: entity.project_name.clone(),
            project_type: entity.project_type.clone(),
            customer_id: entity.customer_id.clone(),
            source_so_id: entity.source_so_id.clone(),
            currency: entity.currency.clone(),
            status: entity.status.clone(),
            expected_start_date: entity.expected_start_date.clone(),
            expected_end_date: entity.expected_end_date.clone(),
            total_costing_amount: entity.total_costing_amount.clone(),
            total_billable_amount: entity.total_billable_amount.clone(),
            total_billed_amount: entity.total_billed_amount.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProjectDto> for Project {
    fn from_create_dto(dto: CreateProjectDto) -> backbone_core::ServiceResult<Self> {
        Ok(Project::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProjectDto> for Project {
    fn apply_update(mut self, dto: UpdateProjectDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.project_name = dto.project_name;
        self.project_type = dto.project_type;
        self.customer_id = dto.customer_id;
        self.source_so_id = dto.source_so_id;
        self.currency = dto.currency;
        self.status = dto.status;
        self.expected_start_date = dto.expected_start_date;
        self.expected_end_date = dto.expected_end_date;
        self.total_costing_amount = dto.total_costing_amount;
        self.total_billable_amount = dto.total_billable_amount;
        self.total_billed_amount = dto.total_billed_amount;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Project here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
