//! ProjectTemplateTask DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ProjectTemplateTask;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ProjectTemplateTask
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProjectTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    #[serde(alias = "expected_time")]
    pub expected_time: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ProjectTemplateTask
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProjectTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    #[serde(alias = "expected_time")]
    pub expected_time: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ProjectTemplateTask
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProjectTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_time")]
    pub expected_time: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
}

impl PatchProjectTemplateTaskDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.template_id.is_some() || self.subject.is_some() || self.task_type.is_some() || self.expected_time.is_some() || self.sequence.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ProjectTemplateTask entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateTaskResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub template_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    pub task_type: Option<String>,
    pub expected_time: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ProjectTemplateTask entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateTaskListResponseDto {
    /// List of items
    pub items: Vec<ProjectTemplateTaskResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProjectTemplateTaskListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProjectTemplateTaskResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProjectTemplateTaskSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub subject: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ProjectTemplateTask> for ProjectTemplateTaskResponseDto {
    fn from(entity: ProjectTemplateTask) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            subject: entity.subject,
            task_type: entity.task_type,
            expected_time: entity.expected_time,
            sequence: entity.sequence,
            metadata: entity.metadata,
        }
    }
}

impl From<ProjectTemplateTask> for ProjectTemplateTaskSummaryDto {
    fn from(entity: ProjectTemplateTask) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            subject: entity.subject,
            created_at,
        }
    }
}

impl From<CreateProjectTemplateTaskDto> for ProjectTemplateTask {
    fn from(dto: CreateProjectTemplateTaskDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            template_id: dto.template_id,
            subject: dto.subject,
            task_type: dto.task_type,
            expected_time: dto.expected_time,
            sequence: dto.sequence,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ProjectTemplateTask> for ProjectTemplateTaskResponseDto {
    fn from(entity: &ProjectTemplateTask) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            template_id: entity.template_id.clone(),
            subject: entity.subject.clone(),
            task_type: entity.task_type.clone(),
            expected_time: entity.expected_time.clone(),
            sequence: entity.sequence.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProjectTemplateTaskDto> for ProjectTemplateTask {
    fn from_create_dto(dto: CreateProjectTemplateTaskDto) -> backbone_core::ServiceResult<Self> {
        Ok(ProjectTemplateTask::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProjectTemplateTaskDto> for ProjectTemplateTask {
    fn apply_update(mut self, dto: UpdateProjectTemplateTaskDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.template_id = dto.template_id;
        self.subject = dto.subject;
        self.task_type = dto.task_type;
        self.expected_time = dto.expected_time;
        self.sequence = dto.sequence;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ProjectTemplateTask here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

