//! Task DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Task;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TaskStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Task
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "project_id")]
    pub project_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_task_id")]
    pub parent_task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    pub status: TaskStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_sale_line_id")]
    pub origin_sale_line_id: Option<Uuid>,
    #[serde(alias = "expected_time")]
    pub expected_time: Decimal,
    pub progress: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Task
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "project_id")]
    pub project_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_task_id")]
    pub parent_task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    pub status: TaskStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "origin_sale_line_id")]
    pub origin_sale_line_id: Option<Uuid>,
    #[serde(alias = "expected_time")]
    pub expected_time: Decimal,
    pub progress: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Task
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "project_id")]
    pub project_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_task_id")]
    pub parent_task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "task_type")]
    pub task_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<TaskStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "origin_sale_line_id")]
    pub origin_sale_line_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expected_time")]
    pub expected_time: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<Decimal>,
}

impl PatchTaskDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.project_id.is_some() || self.parent_task_id.is_some() || self.subject.is_some() || self.task_type.is_some() || self.status.is_some() || self.origin_sale_line_id.is_some() || self.expected_time.is_some() || self.progress.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Task entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaskResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub project_id: Uuid,
    pub parent_task_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    pub task_type: Option<String>,
    pub status: TaskStatus,
    pub origin_sale_line_id: Option<Uuid>,
    pub expected_time: Decimal,
    pub progress: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Task entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaskListResponseDto {
    /// List of items
    pub items: Vec<TaskResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TaskListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TaskResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TaskSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub parent_task_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Task> for TaskResponseDto {
    fn from(entity: Task) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            project_id: entity.project_id,
            parent_task_id: entity.parent_task_id,
            subject: entity.subject,
            task_type: entity.task_type,
            status: entity.status,
            origin_sale_line_id: entity.origin_sale_line_id,
            expected_time: entity.expected_time,
            progress: entity.progress,
            metadata: entity.metadata,
        }
    }
}

impl From<Task> for TaskSummaryDto {
    fn from(entity: Task) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            project_id: entity.project_id,
            parent_task_id: entity.parent_task_id,
            created_at,
        }
    }
}

impl From<CreateTaskDto> for Task {
    fn from(dto: CreateTaskDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            project_id: dto.project_id,
            parent_task_id: dto.parent_task_id,
            subject: dto.subject,
            task_type: dto.task_type,
            status: dto.status,
            origin_sale_line_id: dto.origin_sale_line_id,
            expected_time: dto.expected_time,
            progress: dto.progress,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Task> for TaskResponseDto {
    fn from(entity: &Task) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            project_id: entity.project_id.clone(),
            parent_task_id: entity.parent_task_id.clone(),
            subject: entity.subject.clone(),
            task_type: entity.task_type.clone(),
            status: entity.status.clone(),
            origin_sale_line_id: entity.origin_sale_line_id.clone(),
            expected_time: entity.expected_time.clone(),
            progress: entity.progress.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTaskDto> for Task {
    fn from_create_dto(dto: CreateTaskDto) -> backbone_core::ServiceResult<Self> {
        Ok(Task::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTaskDto> for Task {
    fn apply_update(mut self, dto: UpdateTaskDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.project_id = dto.project_id;
        self.parent_task_id = dto.parent_task_id;
        self.subject = dto.subject;
        self.task_type = dto.task_type;
        self.status = dto.status;
        self.origin_sale_line_id = dto.origin_sale_line_id;
        self.expected_time = dto.expected_time;
        self.progress = dto.progress;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Task here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
