//! TimesheetDetail DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimesheetDetail;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimesheetDetail
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimesheetDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timesheet_id")]
    pub timesheet_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub hours: Decimal,
    #[serde(alias = "billing_rate")]
    pub billing_rate: Decimal,
    #[serde(alias = "costing_rate")]
    pub costing_rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_billable")]
    pub is_billable: bool,
    #[serde(alias = "billable_amount")]
    pub billable_amount: Decimal,
    #[serde(alias = "costing_amount")]
    pub costing_amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimesheetDetail
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimesheetDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "timesheet_id")]
    pub timesheet_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub hours: Decimal,
    #[serde(alias = "billing_rate")]
    pub billing_rate: Decimal,
    #[serde(alias = "costing_rate")]
    pub costing_rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_billable")]
    pub is_billable: bool,
    #[serde(alias = "billable_amount")]
    pub billable_amount: Decimal,
    #[serde(alias = "costing_amount")]
    pub costing_amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimesheetDetail
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimesheetDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "timesheet_id")]
    pub timesheet_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hours: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billing_rate")]
    pub billing_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "costing_rate")]
    pub costing_rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_billable")]
    pub is_billable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billable_amount")]
    pub billable_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "costing_amount")]
    pub costing_amount: Option<Decimal>,
}

impl PatchTimesheetDetailDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.timesheet_id.is_some() || self.activity_type_id.is_some() || self.task_id.is_some() || self.description.is_some() || self.hours.is_some() || self.billing_rate.is_some() || self.costing_rate.is_some() || self.is_billable.is_some() || self.billable_amount.is_some() || self.costing_amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimesheetDetail entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetDetailResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub timesheet_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub description: Option<String>,
    pub hours: Decimal,
    pub billing_rate: Decimal,
    pub costing_rate: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_billable: bool,
    pub billable_amount: Decimal,
    pub costing_amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimesheetDetail entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetDetailListResponseDto {
    /// List of items
    pub items: Vec<TimesheetDetailResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimesheetDetailListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimesheetDetailResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetDetailSummaryDto {
    pub id: Uuid,
    pub timesheet_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimesheetDetail> for TimesheetDetailResponseDto {
    fn from(entity: TimesheetDetail) -> Self {
        Self {
            id: entity.id,
            timesheet_id: entity.timesheet_id,
            activity_type_id: entity.activity_type_id,
            task_id: entity.task_id,
            description: entity.description,
            hours: entity.hours,
            billing_rate: entity.billing_rate,
            costing_rate: entity.costing_rate,
            is_billable: entity.is_billable,
            billable_amount: entity.billable_amount,
            costing_amount: entity.costing_amount,
            metadata: entity.metadata,
        }
    }
}

impl From<TimesheetDetail> for TimesheetDetailSummaryDto {
    fn from(entity: TimesheetDetail) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            timesheet_id: entity.timesheet_id,
            activity_type_id: entity.activity_type_id,
            task_id: entity.task_id,
            created_at,
        }
    }
}

impl From<CreateTimesheetDetailDto> for TimesheetDetail {
    fn from(dto: CreateTimesheetDetailDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            timesheet_id: dto.timesheet_id,
            activity_type_id: dto.activity_type_id,
            task_id: dto.task_id,
            description: dto.description,
            hours: dto.hours,
            billing_rate: dto.billing_rate,
            costing_rate: dto.costing_rate,
            is_billable: dto.is_billable,
            billable_amount: dto.billable_amount,
            costing_amount: dto.costing_amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimesheetDetail> for TimesheetDetailResponseDto {
    fn from(entity: &TimesheetDetail) -> Self {
        Self {
            id: entity.id.clone(),
            timesheet_id: entity.timesheet_id.clone(),
            activity_type_id: entity.activity_type_id.clone(),
            task_id: entity.task_id.clone(),
            description: entity.description.clone(),
            hours: entity.hours.clone(),
            billing_rate: entity.billing_rate.clone(),
            costing_rate: entity.costing_rate.clone(),
            is_billable: entity.is_billable.clone(),
            billable_amount: entity.billable_amount.clone(),
            costing_amount: entity.costing_amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimesheetDetailDto> for TimesheetDetail {
    fn from_create_dto(dto: CreateTimesheetDetailDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimesheetDetail::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimesheetDetailDto> for TimesheetDetail {
    fn apply_update(mut self, dto: UpdateTimesheetDetailDto) -> backbone_core::ServiceResult<Self> {
        self.timesheet_id = dto.timesheet_id;
        self.activity_type_id = dto.activity_type_id;
        self.task_id = dto.task_id;
        self.description = dto.description;
        self.hours = dto.hours;
        self.billing_rate = dto.billing_rate;
        self.costing_rate = dto.costing_rate;
        self.is_billable = dto.is_billable;
        self.billable_amount = dto.billable_amount;
        self.costing_amount = dto.costing_amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimesheetDetail here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
