//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod activity_type_specification;
pub mod project_specification;
pub mod project_template_specification;
pub mod project_template_task_specification;
pub mod task_specification;

// <<< CUSTOM
// END CUSTOM
