//! Domain policy for ActivityType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ActivityType;

/// Domain policy for ActivityType — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ActivityType>` in the `// <<< CUSTOM` zone.
pub type ActivityTypeDomainPolicy = PermitAllPolicy<ActivityType>;

// <<< CUSTOM
// END CUSTOM
