//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod activity_type_domain_policy;
pub mod project_domain_policy;
pub mod project_template_domain_policy;
pub mod project_template_task_domain_policy;
pub mod task_domain_policy;

pub use activity_type_domain_policy::ActivityTypeDomainPolicy;
pub use project_domain_policy::ProjectDomainPolicy;
pub use project_template_domain_policy::ProjectTemplateDomainPolicy;
pub use project_template_task_domain_policy::ProjectTemplateTaskDomainPolicy;
pub use task_domain_policy::TaskDomainPolicy;

// <<< CUSTOM
// END CUSTOM
