//! Domain policy for ProjectTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ProjectTemplate;

/// Domain policy for ProjectTemplate — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ProjectTemplate>` in the `// <<< CUSTOM` zone.
pub type ProjectTemplateDomainPolicy = PermitAllPolicy<ProjectTemplate>;

// <<< CUSTOM
// END CUSTOM
