//! Domain policy for Project aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::Project;

/// Domain policy for Project — enforces business invariants.
pub struct ProjectDomainPolicy;

#[async_trait]
impl DomainPolicy<Project> for ProjectDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // Example:
    // async fn can_delete(&self, entity: &Project) -> PolicyDecision {
    //     if entity.is_locked {
    //         Err("locked project cannot be deleted".into())
    //     } else { Ok(true) }
    // }
    // END CUSTOM
}
