//! Domain policy for Project aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Project;

/// Domain policy for Project — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Project>` in the `// <<< CUSTOM` zone.
pub type ProjectDomainPolicy = PermitAllPolicy<Project>;

// <<< CUSTOM
// END CUSTOM
