//! Application service for ActivityType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `activity_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateActivityTypeDto, UpdateActivityTypeDto};
use crate::domain::entity::ActivityType;
use crate::infrastructure::persistence::ActivityTypeRepository;

/// Application service for ActivityType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `activity_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ActivityTypeServiceCustom {
///     inner: Arc<ActivityTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ActivityTypeService = GenericCrudService<
    ActivityType,
    CreateActivityTypeDto,
    UpdateActivityTypeDto,
    ActivityTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
