//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod activity_type_service;
pub mod project_service;
pub mod project_template_service;
pub mod project_template_task_service;
pub mod task_service;
pub mod timesheet_service;
pub mod timesheet_detail_service;

// <<< CUSTOM
pub mod project_events;
pub mod project_ports;
pub mod project_write_service;
// END CUSTOM

pub use activity_type_service::ActivityTypeService;
pub use project_service::ProjectService;
pub use project_template_service::ProjectTemplateService;
pub use project_template_task_service::ProjectTemplateTaskService;
pub use task_service::TaskService;
pub use timesheet_service::TimesheetService;
pub use timesheet_detail_service::TimesheetDetailService;
// <<< CUSTOM
pub use project_events::{
    LoggingSink, ProjectCompleted, ProjectEvent, ProjectEventSink, TimeLogged, TimesheetBilled,
    TimesheetCancelled,
};
pub use project_ports::{
    BillingPort, InvoiceAck, InvoiceFromTimesheet, InvoiceLineFromTimesheet, ProjectRejected,
};
pub use project_write_service::{
    BillOutcome, NewProject, NewTask, NewTimeLine, NewTimesheet, ProjectError, ProjectWriteService,
};
// END CUSTOM