//! Application service for Project entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `project_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateProjectDto, UpdateProjectDto};
use crate::domain::entity::Project;
use crate::infrastructure::persistence::ProjectRepository;

/// Application service for Project entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `project_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ProjectServiceCustom {
///     inner: Arc<ProjectService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ProjectService = GenericCrudService<
    Project,
    CreateProjectDto,
    UpdateProjectDto,
    ProjectRepository,
>;

// <<< CUSTOM
// END CUSTOM
