//! Application service for Task entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `task_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTaskDto, UpdateTaskDto};
use crate::domain::entity::Task;
use crate::infrastructure::persistence::TaskRepository;

/// Application service for Task entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `task_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TaskServiceCustom {
///     inner: Arc<TaskService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TaskService = GenericCrudService<
    Task,
    CreateTaskDto,
    UpdateTaskDto,
    TaskRepository,
>;

// <<< CUSTOM
// END CUSTOM
