-- ProjectTemplateTask Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the project.project_template_tasks table.
-- Customize this file to add your initial data.

-- INSERT INTO project.project_template_tasks (
--     id,
--     template_id,
--     subject,
--     task_type,
--     expected_time,
--     sequence,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO project.project_template_tasks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

