-- Project Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the project.projects table.
-- Customize this file to add your initial data.

-- INSERT INTO project.projects (
--     id,
--     company_id,
--     project_name,
--     project_type,
--     customer_id,
--     source_so_id,
--     currency,
--     status,
--     expected_start_date,
--     expected_end_date,
--     total_costing_amount,
--     total_billable_amount,
--     total_billed_amount,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO project.projects (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

