-- Task Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the project.tasks table.
-- Customize this file to add your initial data.

-- INSERT INTO project.tasks (
--     id,
--     company_id,
--     project_id,
--     parent_task_id,
--     subject,
--     task_type,
--     status,
--     expected_time,
--     progress,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO project.tasks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

