-- Timesheet Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the project.timesheets table.
-- Customize this file to add your initial data.

-- INSERT INTO project.timesheets (
--     id,
--     company_id,
--     project_id,
--     employee_id,
--     currency,
--     status,
--     total_hours,
--     total_billable_amount,
--     total_costing_amount,
--     invoice_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO project.timesheets (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

