-- TimesheetDetail Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the project.timesheet_details table.
-- Customize this file to add your initial data.

-- INSERT INTO project.timesheet_details (
--     id,
--     timesheet_id,
--     activity_type_id,
--     task_id,
--     description,
--     hours,
--     billing_rate,
--     costing_rate,
--     is_billable,
--     billable_amount,
--     costing_amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO project.timesheet_details (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

