-- Migration: Create activity_types table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.activity_types (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    billing_rate NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (billing_rate >= 0),
    costing_rate NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (costing_rate >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_activity_types_company_id_is_active ON project.activity_types (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_activity_types_metadata_gin ON project.activity_types USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_activity_types_metadata_deleted_at ON project.activity_types ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_activity_types_metadata_created_at ON project.activity_types ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_activity_types_metadata_updated_at ON project.activity_types ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.activity_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS activity_types_insert_audit ON project.activity_types;
CREATE TRIGGER activity_types_insert_audit BEFORE INSERT ON project.activity_types
    FOR EACH ROW EXECUTE FUNCTION project.activity_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS activity_types_update_audit ON project.activity_types;
CREATE TRIGGER activity_types_update_audit BEFORE UPDATE ON project.activity_types
    FOR EACH ROW EXECUTE FUNCTION project.activity_types_audit_timestamp();
