-- Migration: Create timesheet_details table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.timesheet_details (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    timesheet_id UUID NOT NULL,
    activity_type_id UUID,
    task_id UUID,
    description TEXT,
    hours NUMERIC NOT NULL,
    billing_rate NUMERIC NOT NULL DEFAULT 0,
    costing_rate NUMERIC NOT NULL DEFAULT 0,
    is_billable BOOLEAN NOT NULL DEFAULT TRUE,
    billable_amount NUMERIC NOT NULL DEFAULT 0,
    costing_amount NUMERIC NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_timesheet_details_timesheet_id ON project.timesheet_details (timesheet_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_timesheet_details_metadata_gin ON project.timesheet_details USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_timesheet_details_metadata_deleted_at ON project.timesheet_details ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_timesheet_details_metadata_created_at ON project.timesheet_details ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_timesheet_details_metadata_updated_at ON project.timesheet_details ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.timesheet_details_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheet_details_insert_audit ON project.timesheet_details;
CREATE TRIGGER timesheet_details_insert_audit BEFORE INSERT ON project.timesheet_details
    FOR EACH ROW EXECUTE FUNCTION project.timesheet_details_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheet_details_update_audit ON project.timesheet_details;
CREATE TRIGGER timesheet_details_update_audit BEFORE UPDATE ON project.timesheet_details
    FOR EACH ROW EXECUTE FUNCTION project.timesheet_details_audit_timestamp();
