-- Migration: Create projects table
-- Generated by metaphor-schema

-- Create project_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_type') THEN
        CREATE TYPE project_type AS ENUM ('external', 'internal');
    END IF;
END
$$;

-- Create project_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_status') THEN
        CREATE TYPE project_status AS ENUM ('open', 'completed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.projects (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    project_name TEXT NOT NULL,
    project_type project_type NOT NULL DEFAULT 'external',
    customer_id UUID,
    source_so_id UUID,
    currency TEXT NOT NULL DEFAULT 'IDR',
    status project_status NOT NULL DEFAULT 'open',
    expected_start_date TIMESTAMPTZ,
    expected_end_date TIMESTAMPTZ,
    total_costing_amount NUMERIC NOT NULL DEFAULT 0,
    total_billable_amount NUMERIC NOT NULL DEFAULT 0,
    total_billed_amount NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_projects_company_id_status ON project.projects (company_id, status);

CREATE INDEX IF NOT EXISTS idx_projects_customer_id ON project.projects (customer_id);

CREATE INDEX IF NOT EXISTS idx_projects_source_so_id ON project.projects (source_so_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_projects_metadata_gin ON project.projects USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_projects_metadata_deleted_at ON project.projects ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_projects_metadata_created_at ON project.projects ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_projects_metadata_updated_at ON project.projects ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.projects_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS projects_insert_audit ON project.projects;
CREATE TRIGGER projects_insert_audit BEFORE INSERT ON project.projects
    FOR EACH ROW EXECUTE FUNCTION project.projects_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS projects_update_audit ON project.projects;
CREATE TRIGGER projects_update_audit BEFORE UPDATE ON project.projects
    FOR EACH ROW EXECUTE FUNCTION project.projects_audit_timestamp();
