-- Migration: Create project_template_tasks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.project_template_tasks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL,
    subject TEXT NOT NULL,
    task_type TEXT,
    expected_time NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (expected_time >= 0),
    sequence INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_project_template_tasks_template_id ON project.project_template_tasks (template_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_project_template_tasks_metadata_gin ON project.project_template_tasks USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_project_template_tasks_metadata_deleted_at ON project.project_template_tasks ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_project_template_tasks_metadata_created_at ON project.project_template_tasks ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_project_template_tasks_metadata_updated_at ON project.project_template_tasks ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.project_template_tasks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS project_template_tasks_insert_audit ON project.project_template_tasks;
CREATE TRIGGER project_template_tasks_insert_audit BEFORE INSERT ON project.project_template_tasks
    FOR EACH ROW EXECUTE FUNCTION project.project_template_tasks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS project_template_tasks_update_audit ON project.project_template_tasks;
CREATE TRIGGER project_template_tasks_update_audit BEFORE UPDATE ON project.project_template_tasks
    FOR EACH ROW EXECUTE FUNCTION project.project_template_tasks_audit_timestamp();
