-- Migration: Create project_templates table
-- Generated by metaphor-schema

-- Create project_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_type') THEN
        CREATE TYPE project_type AS ENUM ('external', 'internal');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.project_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    template_name TEXT NOT NULL,
    project_type project_type NOT NULL DEFAULT 'external',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_project_templates_company_id_is_active ON project.project_templates (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_project_templates_metadata_gin ON project.project_templates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_project_templates_metadata_deleted_at ON project.project_templates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_project_templates_metadata_created_at ON project.project_templates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_project_templates_metadata_updated_at ON project.project_templates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.project_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS project_templates_insert_audit ON project.project_templates;
CREATE TRIGGER project_templates_insert_audit BEFORE INSERT ON project.project_templates
    FOR EACH ROW EXECUTE FUNCTION project.project_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS project_templates_update_audit ON project.project_templates;
CREATE TRIGGER project_templates_update_audit BEFORE UPDATE ON project.project_templates
    FOR EACH ROW EXECUTE FUNCTION project.project_templates_audit_timestamp();
