-- Enum types for project module
-- Generated by metaphor-schema

-- Create project_type enum type
-- The schema must exist before a type can be created inside it. This
-- migration now qualifies its enums to `project`, so it owns bringing the
-- schema up rather than depending on a later table migration to do it.
CREATE SCHEMA IF NOT EXISTS project;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_type') THEN
        CREATE TYPE project_type AS ENUM ('external', 'internal');
    END IF;
END
$$;

-- Create project_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_status') THEN
        CREATE TYPE project_status AS ENUM ('open', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create task_status enum type
-- `task_status` is NOT a shared vocabulary. This module's task states and the
-- ones another module happens to give the same name are different concepts with
-- disjoint values, so the type is qualified to this module's own schema. An
-- unqualified CREATE TYPE lands in whichever schema the search_path names and
-- the guard below matched the name in ANY schema, so whichever module migrated
-- first won globally and the other's columns failed on a value the type it
-- found does not have.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                   WHERE t.typname = 'task_status' AND n.nspname = 'project') THEN
        CREATE TYPE project.task_status AS ENUM ('open', 'working', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create timesheet_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_status') THEN
        CREATE TYPE timesheet_status AS ENUM ('draft', 'submitted', 'billed', 'cancelled');
    END IF;
END
$$;

