-- Migration: Create tasks table
-- Generated by metaphor-schema

-- Create task_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM ('open', 'working', 'completed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS project;

CREATE TABLE IF NOT EXISTS project.tasks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    project_id UUID NOT NULL,
    parent_task_id UUID,
    subject TEXT NOT NULL,
    task_type TEXT,
    status task_status NOT NULL DEFAULT 'open',
    expected_time NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (expected_time >= 0),
    progress NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (progress >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id_status ON project.tasks (project_id, status);

CREATE INDEX IF NOT EXISTS idx_tasks_parent_task_id ON project.tasks (parent_task_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_tasks_metadata_gin ON project.tasks USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_tasks_metadata_deleted_at ON project.tasks ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_tasks_metadata_created_at ON project.tasks ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_tasks_metadata_updated_at ON project.tasks ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION project.tasks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tasks_insert_audit ON project.tasks;
CREATE TRIGGER tasks_insert_audit BEFORE INSERT ON project.tasks
    FOR EACH ROW EXECUTE FUNCTION project.tasks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tasks_update_audit ON project.tasks;
CREATE TRIGGER tasks_update_audit BEFORE UPDATE ON project.tasks
    FOR EACH ROW EXECUTE FUNCTION project.tasks_audit_timestamp();
