-- Enum types for project module
-- Generated by metaphor-schema

-- Create project_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_type') THEN
        CREATE TYPE project_type AS ENUM ('external', 'internal');
    END IF;
END
$$;

-- Create project_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_status') THEN
        CREATE TYPE project_status AS ENUM ('open', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create task_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM ('open', 'working', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create timesheet_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_status') THEN
        CREATE TYPE timesheet_status AS ENUM ('draft', 'submitted', 'billed', 'cancelled');
    END IF;
END
$$;

