-- Audit Triggers Migration for project module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ActivityType (project.activity_types)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.activity_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS activity_types_insert_audit ON project.activity_types;
CREATE TRIGGER activity_types_insert_audit BEFORE INSERT ON project.activity_types
    FOR EACH ROW EXECUTE FUNCTION project.activity_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS activity_types_update_audit ON project.activity_types;
CREATE TRIGGER activity_types_update_audit BEFORE UPDATE ON project.activity_types
    FOR EACH ROW EXECUTE FUNCTION project.activity_types_audit_timestamp();

-- ==============================================================================
-- Table: Project (project.projects)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.projects_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS projects_insert_audit ON project.projects;
CREATE TRIGGER projects_insert_audit BEFORE INSERT ON project.projects
    FOR EACH ROW EXECUTE FUNCTION project.projects_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS projects_update_audit ON project.projects;
CREATE TRIGGER projects_update_audit BEFORE UPDATE ON project.projects
    FOR EACH ROW EXECUTE FUNCTION project.projects_audit_timestamp();

-- ==============================================================================
-- Table: ProjectTemplate (project.project_templates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.project_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS project_templates_insert_audit ON project.project_templates;
CREATE TRIGGER project_templates_insert_audit BEFORE INSERT ON project.project_templates
    FOR EACH ROW EXECUTE FUNCTION project.project_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS project_templates_update_audit ON project.project_templates;
CREATE TRIGGER project_templates_update_audit BEFORE UPDATE ON project.project_templates
    FOR EACH ROW EXECUTE FUNCTION project.project_templates_audit_timestamp();

-- ==============================================================================
-- Table: ProjectTemplateTask (project.project_template_tasks)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.project_template_tasks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS project_template_tasks_insert_audit ON project.project_template_tasks;
CREATE TRIGGER project_template_tasks_insert_audit BEFORE INSERT ON project.project_template_tasks
    FOR EACH ROW EXECUTE FUNCTION project.project_template_tasks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS project_template_tasks_update_audit ON project.project_template_tasks;
CREATE TRIGGER project_template_tasks_update_audit BEFORE UPDATE ON project.project_template_tasks
    FOR EACH ROW EXECUTE FUNCTION project.project_template_tasks_audit_timestamp();

-- ==============================================================================
-- Table: Task (project.tasks)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.tasks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tasks_insert_audit ON project.tasks;
CREATE TRIGGER tasks_insert_audit BEFORE INSERT ON project.tasks
    FOR EACH ROW EXECUTE FUNCTION project.tasks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tasks_update_audit ON project.tasks;
CREATE TRIGGER tasks_update_audit BEFORE UPDATE ON project.tasks
    FOR EACH ROW EXECUTE FUNCTION project.tasks_audit_timestamp();

-- ==============================================================================
-- Table: Timesheet (project.timesheets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.timesheets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheets_insert_audit ON project.timesheets;
CREATE TRIGGER timesheets_insert_audit BEFORE INSERT ON project.timesheets
    FOR EACH ROW EXECUTE FUNCTION project.timesheets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheets_update_audit ON project.timesheets;
CREATE TRIGGER timesheets_update_audit BEFORE UPDATE ON project.timesheets
    FOR EACH ROW EXECUTE FUNCTION project.timesheets_audit_timestamp();

-- ==============================================================================
-- Table: TimesheetDetail (project.timesheet_details)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION project.timesheet_details_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheet_details_insert_audit ON project.timesheet_details;
CREATE TRIGGER timesheet_details_insert_audit BEFORE INSERT ON project.timesheet_details
    FOR EACH ROW EXECUTE FUNCTION project.timesheet_details_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheet_details_update_audit ON project.timesheet_details;
CREATE TRIGGER timesheet_details_update_audit BEFORE UPDATE ON project.timesheet_details
    FOR EACH ROW EXECUTE FUNCTION project.timesheet_details_audit_timestamp();

