-- Company RLS fence for project module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for project.activity_types
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE project.activity_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE project.activity_types FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS activity_types_company_isolation ON project.activity_types;
CREATE POLICY activity_types_company_isolation ON project.activity_types
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for project.projects
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE project.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project.projects FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS projects_company_isolation ON project.projects;
CREATE POLICY projects_company_isolation ON project.projects
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for project.project_templates
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE project.project_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE project.project_templates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_templates_company_isolation ON project.project_templates;
CREATE POLICY project_templates_company_isolation ON project.project_templates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for project.tasks
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE project.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project.tasks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tasks_company_isolation ON project.tasks;
CREATE POLICY tasks_company_isolation ON project.tasks
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for project.timesheets
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE project.timesheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE project.timesheets FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timesheets_company_isolation ON project.timesheets;
CREATE POLICY timesheets_company_isolation ON project.timesheets
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

