//! Event handler trait for ActivityType events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ActivityTypeEvent;

/// Event handler for ActivityType events.
/// Implement this trait to react to ActivityType lifecycle events.
pub trait ActivityTypeEventHandler: EventHandler<ActivityTypeEvent> {}
