//! Domain events for ActivityType entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ActivityType;

/// Domain events for ActivityType — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ActivityType>)` variant.
pub type ActivityTypeEvent = CrudEvent<ActivityType>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ActivityType events.
pub type ActivityTypeEventPublisher = Arc<dyn CrudEventPublisher<ActivityType> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopActivityTypeEventPublisher = NoOpCrudEventPublisher<ActivityType>;
