//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod activity_type_events;
pub mod activity_type_event_handlers;
pub mod project_events;
pub mod project_event_handlers;
pub mod project_template_events;
pub mod project_template_event_handlers;
pub mod project_template_task_events;
pub mod project_template_task_event_handlers;
pub mod task_events;
pub mod task_event_handlers;

pub use activity_type_events::{ActivityTypeEvent, ActivityTypeEventPublisher, NoopActivityTypeEventPublisher};
pub use activity_type_event_handlers::ActivityTypeEventHandler;
pub use project_events::{ProjectEvent, ProjectEventPublisher, NoopProjectEventPublisher};
pub use project_event_handlers::ProjectEventHandler;
pub use project_template_events::{ProjectTemplateEvent, ProjectTemplateEventPublisher, NoopProjectTemplateEventPublisher};
pub use project_template_event_handlers::ProjectTemplateEventHandler;
pub use project_template_task_events::{ProjectTemplateTaskEvent, ProjectTemplateTaskEventPublisher, NoopProjectTemplateTaskEventPublisher};
pub use project_template_task_event_handlers::ProjectTemplateTaskEventHandler;
pub use task_events::{TaskEvent, TaskEventPublisher, NoopTaskEventPublisher};
pub use task_event_handlers::TaskEventHandler;

// <<< CUSTOM
// END CUSTOM
