//! Event handler trait for ProjectTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProjectTemplateEvent;

/// Event handler for ProjectTemplate events.
/// Implement this trait to react to ProjectTemplate lifecycle events.
pub trait ProjectTemplateEventHandler: EventHandler<ProjectTemplateEvent> {}
