//! Event handler trait for Project events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProjectEvent;

/// Event handler for Project events.
/// Implement this trait to react to Project lifecycle events.
pub trait ProjectEventHandler: EventHandler<ProjectEvent> {}
