//! Domain events for Project entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Project;

/// Domain events for Project — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Project>)` variant.
pub type ProjectEvent = CrudEvent<Project>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Project events.
pub type ProjectEventPublisher = Arc<dyn CrudEventPublisher<Project> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopProjectEventPublisher = NoOpCrudEventPublisher<Project>;
