//! Domain events for ProjectTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ProjectTemplate;

/// Domain events for ProjectTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ProjectTemplate>)` variant.
pub type ProjectTemplateEvent = CrudEvent<ProjectTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ProjectTemplate events.
pub type ProjectTemplateEventPublisher = Arc<dyn CrudEventPublisher<ProjectTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopProjectTemplateEventPublisher = NoOpCrudEventPublisher<ProjectTemplate>;
