//! Event handler trait for ProjectTemplateTask events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProjectTemplateTaskEvent;

/// Event handler for ProjectTemplateTask events.
/// Implement this trait to react to ProjectTemplateTask lifecycle events.
pub trait ProjectTemplateTaskEventHandler: EventHandler<ProjectTemplateTaskEvent> {}
