//! Event handler trait for Task events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TaskEvent;

/// Event handler for Task events.
/// Implement this trait to react to Task lifecycle events.
pub trait TaskEventHandler: EventHandler<TaskEvent> {}
