//! Domain events for Task entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Task;

/// Domain events for Task — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Task>)` variant.
pub type TaskEvent = CrudEvent<Task>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Task events.
pub type TaskEventPublisher = Arc<dyn CrudEventPublisher<Task> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTaskEventPublisher = NoOpCrudEventPublisher<Task>;
