//! Event handler trait for TimesheetDetail events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimesheetDetailEvent;

/// Event handler for TimesheetDetail events.
/// Implement this trait to react to TimesheetDetail lifecycle events.
pub trait TimesheetDetailEventHandler: EventHandler<TimesheetDetailEvent> {}
