//! Domain events for TimesheetDetail entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimesheetDetail;

/// Domain events for TimesheetDetail — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimesheetDetail>)` variant.
pub type TimesheetDetailEvent = CrudEvent<TimesheetDetail>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimesheetDetail events.
pub type TimesheetDetailEventPublisher = Arc<dyn CrudEventPublisher<TimesheetDetail> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimesheetDetailEventPublisher = NoOpCrudEventPublisher<TimesheetDetail>;
