//! Event subscriber type aliases for Project module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::ActivityTypeEvent;
use crate::domain::event::ProjectEvent;
use crate::domain::event::ProjectTemplateEvent;
use crate::domain::event::ProjectTemplateTaskEvent;
use crate::domain::event::TaskEvent;

/// Subscriber for ActivityType events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ActivityTypeEventSubscriber = GenericEventSubscriber<ActivityTypeEvent>;

/// Subscriber for Project events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProjectEventSubscriber = GenericEventSubscriber<ProjectEvent>;

/// Subscriber for ProjectTemplate events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProjectTemplateEventSubscriber = GenericEventSubscriber<ProjectTemplateEvent>;

/// Subscriber for ProjectTemplateTask events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProjectTemplateTaskEventSubscriber = GenericEventSubscriber<ProjectTemplateTaskEvent>;

/// Subscriber for Task events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type TaskEventSubscriber = GenericEventSubscriber<TaskEvent>;

// <<< CUSTOM
// END CUSTOM
