//! Project Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::ActivityTypeEventSubscriber;
pub use handlers::ProjectEventSubscriber;
pub use handlers::ProjectTemplateEventSubscriber;
pub use handlers::ProjectTemplateTaskEventSubscriber;
pub use handlers::TaskEventSubscriber;
pub use handlers::TimesheetEventSubscriber;
pub use handlers::TimesheetDetailEventSubscriber;
