//! ActivityType seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ActivityType data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ACTIVITYTYPE SEEDER
// ============================================================================

/// Seeder for activity_type
pub struct SeedActivityTypeSeeder;

impl SeedActivityTypeSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedActivityTypeSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedActivityTypeSeeder {
    fn name(&self) -> &'static str {
        "SeedActivityTypeSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if project.activity_types table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM project.activity_types")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/activity_type_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM project.activity_types")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
