//! Database seeders for the project module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod activity_type_seeder;
mod project_seeder;
mod project_template_seeder;
mod project_template_task_seeder;
mod task_seeder;
mod timesheet_seeder;
mod timesheet_detail_seeder;

pub use activity_type_seeder::SeedActivityTypeSeeder;
pub use project_seeder::SeedProjectSeeder;
pub use project_template_seeder::SeedProjectTemplateSeeder;
pub use project_template_task_seeder::SeedProjectTemplateTaskSeeder;
pub use task_seeder::SeedTaskSeeder;
pub use timesheet_seeder::SeedTimesheetSeeder;
pub use timesheet_detail_seeder::SeedTimesheetDetailSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>

