//! ProjectTemplateTask seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ProjectTemplateTask data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PROJECTTEMPLATETASK SEEDER
// ============================================================================

/// Seeder for project_template_task
pub struct SeedProjectTemplateTaskSeeder;

impl SeedProjectTemplateTaskSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedProjectTemplateTaskSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedProjectTemplateTaskSeeder {
    fn name(&self) -> &'static str {
        "SeedProjectTemplateTaskSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if project.project_template_tasks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM project.project_template_tasks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/project_template_task_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM project.project_template_tasks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
