//! TimesheetDetail seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TimesheetDetail data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TIMESHEETDETAIL SEEDER
// ============================================================================

/// Seeder for timesheet_detail
pub struct SeedTimesheetDetailSeeder;

impl SeedTimesheetDetailSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTimesheetDetailSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTimesheetDetailSeeder {
    fn name(&self) -> &'static str {
        "SeedTimesheetDetailSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if project.timesheet_details table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM project.timesheet_details")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/timesheet_detail_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM project.timesheet_details")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

