//! Repository trait for ActivityType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ActivityType aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ActivityType, ActivityTypeStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ActivityTypePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ActivityTypePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ActivityTypePaginatedResult {
    pub data: Vec<ActivityType>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ActivityTypeFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub status: Option<ActivityTypeStatus>,
}

impl ActivityTypeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.status.is_some()
    }
}

/// Repository trait for ActivityType aggregate
///
/// This trait defines the persistence contract for ActivityType entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ActivityTypeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new activity_type entity
    async fn save(&self, entity: &ActivityType) -> Result<ActivityType>;

    /// Find activity_type by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ActivityType>>;

    /// Find all activity_type entities
    async fn find_all(&self) -> Result<Vec<ActivityType>>;

    /// Update activity_type by ID
    async fn update(&self, id: &str, entity: &ActivityType) -> Result<Option<ActivityType>>;

    /// Delete activity_type by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List activity_type with pagination
    async fn list(&self, params: ActivityTypePaginationParams) -> Result<ActivityTypePaginatedResult>;

    /// List activity_type with pagination and filters
    async fn list_with_filters(&self, params: ActivityTypePaginationParams, filters: ActivityTypeFilter) -> Result<ActivityTypePaginatedResult>;

    /// Count all activity_type entities
    async fn count(&self) -> Result<u64>;

    /// Count activity_type entities matching filters
    async fn count_with_filters(&self, filters: ActivityTypeFilter) -> Result<u64>;

    /// Check if activity_type exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete activity_type by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted activity_type by ID
    async fn restore(&self, id: &str) -> Result<Option<ActivityType>>;

    /// List soft-deleted activity_type entities
    async fn list_deleted(&self, params: ActivityTypePaginationParams) -> Result<ActivityTypePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save activity_type entities
    async fn bulk_save(&self, entities: &[ActivityType]) -> Result<Vec<ActivityType>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
