//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod activity_type_repository;
pub mod project_repository;
pub mod project_template_repository;
pub mod project_template_task_repository;
pub mod task_repository;

// Re-exports
pub use activity_type_repository::{
    ActivityTypeRepository,
    ActivityTypePaginationParams,
    ActivityTypePaginatedResult,
    ActivityTypeFilter,
};
pub use project_repository::{
    ProjectRepository,
    ProjectPaginationParams,
    ProjectPaginatedResult,
    ProjectFilter,
};
pub use project_template_repository::{
    ProjectTemplateRepository,
    ProjectTemplatePaginationParams,
    ProjectTemplatePaginatedResult,
    ProjectTemplateFilter,
};
pub use project_template_task_repository::{
    ProjectTemplateTaskRepository,
    ProjectTemplateTaskPaginationParams,
    ProjectTemplateTaskPaginatedResult,
    ProjectTemplateTaskFilter,
};
pub use task_repository::{
    TaskRepository,
    TaskPaginationParams,
    TaskPaginatedResult,
    TaskFilter,
};
