//! Repository trait for ProjectTemplateTask aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ProjectTemplateTask aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ProjectTemplateTask;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProjectTemplateTaskPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ProjectTemplateTaskPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ProjectTemplateTaskPaginatedResult {
    pub data: Vec<ProjectTemplateTask>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProjectTemplateTaskFilter {
    pub template_id: Option<Uuid>,
    pub subject: Option<String>,
    pub task_type: Option<String>,
}

impl ProjectTemplateTaskFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.template_id.is_some() || self.subject.is_some() || self.task_type.is_some()
    }
}

/// Repository trait for ProjectTemplateTask aggregate
///
/// This trait defines the persistence contract for ProjectTemplateTask entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ProjectTemplateTaskRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new project_template_task entity
    async fn save(&self, entity: &ProjectTemplateTask) -> Result<ProjectTemplateTask>;

    /// Find project_template_task by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ProjectTemplateTask>>;

    /// Find all project_template_task entities
    async fn find_all(&self) -> Result<Vec<ProjectTemplateTask>>;

    /// Update project_template_task by ID
    async fn update(&self, id: &str, entity: &ProjectTemplateTask) -> Result<Option<ProjectTemplateTask>>;

    /// Delete project_template_task by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List project_template_task with pagination
    async fn list(&self, params: ProjectTemplateTaskPaginationParams) -> Result<ProjectTemplateTaskPaginatedResult>;

    /// List project_template_task with pagination and filters
    async fn list_with_filters(&self, params: ProjectTemplateTaskPaginationParams, filters: ProjectTemplateTaskFilter) -> Result<ProjectTemplateTaskPaginatedResult>;

    /// Count all project_template_task entities
    async fn count(&self) -> Result<u64>;

    /// Count project_template_task entities matching filters
    async fn count_with_filters(&self, filters: ProjectTemplateTaskFilter) -> Result<u64>;

    /// Check if project_template_task exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete project_template_task by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted project_template_task by ID
    async fn restore(&self, id: &str) -> Result<Option<ProjectTemplateTask>>;

    /// List soft-deleted project_template_task entities
    async fn list_deleted(&self, params: ProjectTemplateTaskPaginationParams) -> Result<ProjectTemplateTaskPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save project_template_task entities
    async fn bulk_save(&self, entities: &[ProjectTemplateTask]) -> Result<Vec<ProjectTemplateTask>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
