//! Repository trait for Project aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Project aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Project, ProjectStatus, ProjectType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProjectPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ProjectPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ProjectPaginatedResult {
    pub data: Vec<Project>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProjectFilter {
    pub company_id: Option<Uuid>,
    pub project_name: Option<String>,
    pub project_type: Option<ProjectType>,
    pub customer_id: Option<Uuid>,
    pub source_so_id: Option<Uuid>,
    pub currency: Option<String>,
    pub status: Option<ProjectStatus>,
    pub notes: Option<String>,
}

impl ProjectFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.project_name.is_some() || self.project_type.is_some() || self.customer_id.is_some() || self.source_so_id.is_some() || self.currency.is_some() || self.status.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Project aggregate
///
/// This trait defines the persistence contract for Project entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ProjectRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new project entity
    async fn save(&self, entity: &Project) -> Result<Project>;

    /// Find project by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Project>>;

    /// Find all project entities
    async fn find_all(&self) -> Result<Vec<Project>>;

    /// Update project by ID
    async fn update(&self, id: &str, entity: &Project) -> Result<Option<Project>>;

    /// Delete project by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List project with pagination
    async fn list(&self, params: ProjectPaginationParams) -> Result<ProjectPaginatedResult>;

    /// List project with pagination and filters
    async fn list_with_filters(&self, params: ProjectPaginationParams, filters: ProjectFilter) -> Result<ProjectPaginatedResult>;

    /// Count all project entities
    async fn count(&self) -> Result<u64>;

    /// Count project entities matching filters
    async fn count_with_filters(&self, filters: ProjectFilter) -> Result<u64>;

    /// Check if project exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete project by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted project by ID
    async fn restore(&self, id: &str) -> Result<Option<Project>>;

    /// List soft-deleted project entities
    async fn list_deleted(&self, params: ProjectPaginationParams) -> Result<ProjectPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save project entities
    async fn bulk_save(&self, entities: &[Project]) -> Result<Vec<Project>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
