//! Repository trait for Task aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Task aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Task, TaskStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaskPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TaskPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TaskPaginatedResult {
    pub data: Vec<Task>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TaskFilter {
    pub company_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    pub parent_task_id: Option<Uuid>,
    pub subject: Option<String>,
    pub task_type: Option<String>,
    pub status: Option<TaskStatus>,
    pub origin_sale_line_id: Option<Uuid>,
}

impl TaskFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.project_id.is_some() || self.parent_task_id.is_some() || self.subject.is_some() || self.task_type.is_some() || self.status.is_some() || self.origin_sale_line_id.is_some()
    }
}

/// Repository trait for Task aggregate
///
/// This trait defines the persistence contract for Task entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TaskRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new task entity
    async fn save(&self, entity: &Task) -> Result<Task>;

    /// Find task by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Task>>;

    /// Find all task entities
    async fn find_all(&self) -> Result<Vec<Task>>;

    /// Update task by ID
    async fn update(&self, id: &str, entity: &Task) -> Result<Option<Task>>;

    /// Delete task by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List task with pagination
    async fn list(&self, params: TaskPaginationParams) -> Result<TaskPaginatedResult>;

    /// List task with pagination and filters
    async fn list_with_filters(&self, params: TaskPaginationParams, filters: TaskFilter) -> Result<TaskPaginatedResult>;

    /// Count all task entities
    async fn count(&self) -> Result<u64>;

    /// Count task entities matching filters
    async fn count_with_filters(&self, filters: TaskFilter) -> Result<u64>;

    /// Check if task exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete task by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted task by ID
    async fn restore(&self, id: &str) -> Result<Option<Task>>;

    /// List soft-deleted task entities
    async fn list_deleted(&self, params: TaskPaginationParams) -> Result<TaskPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save task entities
    async fn bulk_save(&self, entities: &[Task]) -> Result<Vec<Task>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
