//! Repository trait for TimesheetDetail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimesheetDetail aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::TimesheetDetail;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetDetailPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimesheetDetailPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimesheetDetailPaginatedResult {
    pub data: Vec<TimesheetDetail>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetDetailFilter {
    pub company_id: Option<Uuid>,
    pub timesheet_id: Option<Uuid>,
    pub activity_type_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub description: Option<String>,
    pub is_billable: Option<bool>,
}

impl TimesheetDetailFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.timesheet_id.is_some() || self.activity_type_id.is_some() || self.task_id.is_some() || self.description.is_some() || self.is_billable.is_some()
    }
}

/// Repository trait for TimesheetDetail aggregate
///
/// This trait defines the persistence contract for TimesheetDetail entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimesheetDetailRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timesheet_detail entity
    async fn save(&self, entity: &TimesheetDetail) -> Result<TimesheetDetail>;

    /// Find timesheet_detail by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimesheetDetail>>;

    /// Find all timesheet_detail entities
    async fn find_all(&self) -> Result<Vec<TimesheetDetail>>;

    /// Update timesheet_detail by ID
    async fn update(&self, id: &str, entity: &TimesheetDetail) -> Result<Option<TimesheetDetail>>;

    /// Delete timesheet_detail by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timesheet_detail with pagination
    async fn list(&self, params: TimesheetDetailPaginationParams) -> Result<TimesheetDetailPaginatedResult>;

    /// List timesheet_detail with pagination and filters
    async fn list_with_filters(&self, params: TimesheetDetailPaginationParams, filters: TimesheetDetailFilter) -> Result<TimesheetDetailPaginatedResult>;

    /// Count all timesheet_detail entities
    async fn count(&self) -> Result<u64>;

    /// Count timesheet_detail entities matching filters
    async fn count_with_filters(&self, filters: TimesheetDetailFilter) -> Result<u64>;

    /// Check if timesheet_detail exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timesheet_detail by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timesheet_detail by ID
    async fn restore(&self, id: &str) -> Result<Option<TimesheetDetail>>;

    /// List soft-deleted timesheet_detail entities
    async fn list_deleted(&self, params: TimesheetDetailPaginationParams) -> Result<TimesheetDetailPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timesheet_detail entities
    async fn bulk_save(&self, entities: &[TimesheetDetail]) -> Result<Vec<TimesheetDetail>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
