//! Repository for ActivityType entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ActivityType SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ActivityType, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ActivityType;

/// Table name for ActivityType entities
pub const TABLE_NAME: &str = "project.activity_types";

/// Repository for ActivityType entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ActivityTypeRepository(
    backbone_orm::GenericCrudRepository<ActivityType, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ActivityTypeRepository {
    type Target = backbone_orm::GenericCrudRepository<ActivityType, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ActivityTypeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// An activity type's default rates — the fallback a timesheet line snapshots when it doesn't carry
/// its own explicit rate.
pub struct ActivityRatesRow {
    pub billing_rate: Decimal,
    pub costing_rate: Decimal,
}

/// Hand-written ActivityType SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ActivityTypeRepository {
    /// Read an activity type's default rates. `Ok(None)` = no such activity type in scope, in which
    /// case the caller keeps whatever rate it already had (a zero default).
    ///
    /// ID-only, read outside a tx: it rides a connection carrying the caller's `app.company_id`, so
    /// another company's activity type is simply not found.
    pub async fn find_rates(
        &self,
        pool: &PgPool,
        activity_type_id: Uuid,
    ) -> Result<Option<ActivityRatesRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query("SELECT billing_rate, costing_rate FROM project.activity_types WHERE id=$1")
                .bind(activity_type_id),
        )
        .await?;
        Ok(row.map(|r| ActivityRatesRow {
            billing_rate: r.get("billing_rate"), costing_rate: r.get("costing_rate"),
        }))
    }
}

backbone_core::impl_crud_repository!(ActivityTypeRepository, ActivityType, soft_delete);
