//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod activity_type_repository;
mod project_repository;
mod project_template_repository;
mod project_template_task_repository;
mod task_repository;

// Custom persistence modules
// <<< CUSTOM
// The hand-written project SQL's parameter/projection types (see the `*_repository` modules, all
// declared `user_owned` in metaphor.codegen.yaml). `converged_timesheet_repository` is declared
// HERE (inside the CUSTOM block) because the module declaration list above is regenerated —
// the repo itself is user-owned and never regenerated.
pub mod converged_timesheet_repository;
pub use converged_timesheet_repository::{
    ClearInvoiceRow, ConvergedBillableLine, ConvergedTimesheetRepository, ProjectFinancialSums,
    StampInvoiceRow,
};
pub use project_repository::{
    NewProjectRow, ProjectCompletionRow, ProjectFinancialsRow, ProjectScopeRow,
};
pub use project_template_repository::TemplateRow;
pub use project_template_task_repository::TemplateTaskRow;
pub use task_repository::{NewTaskRow, TaskScopeRow};
// END CUSTOM

// Re-exports
pub use activity_type_repository::ActivityTypeRepository;
pub use project_repository::ProjectRepository;
pub use project_template_repository::ProjectTemplateRepository;
pub use project_template_task_repository::ProjectTemplateTaskRepository;
pub use task_repository::TaskRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
