//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod activity_type_repository;
mod project_repository;
mod project_template_repository;
mod project_template_task_repository;
mod task_repository;
mod timesheet_repository;
mod timesheet_detail_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use activity_type_repository::ActivityTypeRepository;
pub use project_repository::ProjectRepository;
pub use project_template_repository::ProjectTemplateRepository;
pub use project_template_task_repository::ProjectTemplateTaskRepository;
pub use task_repository::TaskRepository;
pub use timesheet_repository::TimesheetRepository;
pub use timesheet_detail_repository::TimesheetDetailRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written project SQL's parameter/projection types (see the seven `*_repository` modules, all
// declared `user_owned` in metaphor.codegen.yaml).
pub use activity_type_repository::ActivityRatesRow;
pub use project_repository::{
    NewProjectRow, ProjectCompletionRow, ProjectScopeRow, ProjectTimeLogRow,
};
pub use project_template_repository::TemplateRow;
pub use project_template_task_repository::TemplateTaskRow;
pub use task_repository::NewTaskRow;
pub use timesheet_detail_repository::{BillableLineRow, NewTimesheetDetailRow};
pub use timesheet_repository::{NewTimesheetRow, TimesheetBillingRow, TimesheetCancelRow};
// END CUSTOM