//! Repository for ProjectTemplateTask entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ProjectTemplateTask;

/// Table name for ProjectTemplateTask entities
pub const TABLE_NAME: &str = "project.project_template_tasks";

/// Repository for ProjectTemplateTask entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectTemplateTaskRepository(
    backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectTemplateTaskRepository {
    type Target = backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectTemplateTaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ProjectTemplateTaskRepository, ProjectTemplateTask, soft_delete);
