//! Repository for Project entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Project;

/// Table name for Project entities
pub const TABLE_NAME: &str = "project.projects";

/// Repository for Project entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectRepository(
    backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectRepository {
    type Target = backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ProjectRepository, Project, soft_delete);
