//! Repository for Project entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Project SQL — including the status-gated roll-up/reversal that keeps a
//! project's margin honest (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Project;

/// Table name for Project entities
pub const TABLE_NAME: &str = "project.projects";

/// Repository for Project entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectRepository(
    backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectRepository {
    type Target = backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a project open writes.
///
/// Mirrors the raw column shape rather than the `Project` entity: `project_type` is cast at the DB
/// (`$4::project_type`) and `status` is hard-coded `open`, so neither is a free parameter.
pub struct NewProjectRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_name: &'a str,
    pub project_type: &'a str,
    pub customer_id: Option<Uuid>,
    pub source_so_id: Option<Uuid>,
    pub currency: &'a str,
}

/// A live project's company + delivery state — what the task path reads before it writes.
pub struct ProjectScopeRow {
    pub company_id: Uuid,
    pub status: String,
}

/// What the time-log path reads before it writes: adds the project's default currency.
pub struct ProjectTimeLogRow {
    pub company_id: Uuid,
    pub currency: String,
    pub status: String,
}

/// The final roll-ups captured as a project completes — what `ProjectCompleted` announces.
pub struct ProjectCompletionRow {
    pub company_id: Uuid,
    pub total_billable_amount: Decimal,
    pub total_costing_amount: Decimal,
}

/// Hand-written Project SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ProjectRepository {
    /// Open a project.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK (a non-request caller has no
    /// ambient scope otherwise).
    pub async fn insert_project(
        &self,
        pool: &PgPool,
        p: &NewProjectRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO project.projects
                     (id, company_id, project_name, project_type, customer_id, source_so_id, currency, status)
                   VALUES ($1,$2,$3,$4::project_type,$5,$6,$7,'open'::project_status)"#,
            )
            .bind(p.id).bind(p.company_id).bind(p.project_name).bind(p.project_type)
            .bind(p.customer_id).bind(p.source_so_id).bind(p.currency),
        )
        .await?;
        Ok(())
    }

    /// Read a live project's company + status — the task path's lookup. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's project is simply not found. The company
    /// comes back on the row so the caller can bind the follow-on INSERT to it explicitly.
    pub async fn find_scope_by_id(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectScopeRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, status::text AS status FROM project.projects
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectScopeRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Read a live project's company, default currency + status — the time-log path's lookup. ID-only,
    /// fenced as [`Self::find_scope_by_id`]; the company it returns is bound onto the caller's tx.
    pub async fn find_for_time_log(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectTimeLogRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, currency, status::text AS status FROM project.projects
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectTimeLogRow {
            company_id: r.get("company_id"), currency: r.get("currency"), status: r.get("status"),
        }))
    }

    /// Roll a timesheet's billable + costing up onto the project. Returns rows affected: 0 = the caller
    /// must roll back.
    ///
    /// The status guard is IN this statement, not just in the caller's early read: the UPDATE takes the
    /// project row lock and matches only while status='open', so a `complete_project` that commits
    /// between that read and this loses the race — this hits 0 rows and the whole timesheet insert rolls
    /// back. Without it, time could land on a completed project, growing the roll-up past the "final"
    /// numbers `ProjectCompleted` already published and leaving a billable orphan sheet on a closed
    /// project (maturity council 2026-07-06).
    ///
    /// Takes the CALLER'S connection so this and the timesheet insert commit as ONE unit. The caller has
    /// already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn roll_up_open(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        billable: Decimal,
        costing: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.projects
               SET total_billable_amount = total_billable_amount + $2,
                   total_costing_amount  = total_costing_amount  + $3
               WHERE id=$1 AND status='open'::project_status"#,
        )
        .bind(project_id).bind(billable).bind(costing)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Reverse a cancelled timesheet's billable + costing off the project — the roll-up's reverse gear.
    /// Returns rows affected: 0 = the caller must roll back.
    ///
    /// Gated on an OPEN project, so a completed project's "final" totals stay final. Same
    /// caller-owned-tx contract as [`Self::roll_up_open`].
    pub async fn reverse_roll_up_open(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        billable: Decimal,
        costing: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.projects
               SET total_billable_amount = total_billable_amount - $2,
                   total_costing_amount  = total_costing_amount  - $3
               WHERE id=$1 AND status='open'::project_status"#,
        )
        .bind(project_id).bind(billable).bind(costing)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Read the project's customer — who the timesheet bills to. `Ok(None)` = an internal project with
    /// nobody to bill (the column is nullable).
    ///
    /// ID-only, read outside a tx. Under HTTP the request-dedicated connection carries the scope; an
    /// EVENT/job caller must wrap it in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn find_customer_id(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar::<_, Option<Uuid>>("SELECT customer_id FROM project.projects WHERE id=$1")
                .bind(project_id),
        )
        .await
    }

    /// Roll a billed amount up onto the project's billed total.
    ///
    /// Takes the CALLER'S connection so this and the timesheet's `submitted → billed` flip commit as ONE
    /// unit. The caller has already bound the company on it — don't re-bind here.
    pub async fn add_billed(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        amount: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE project.projects SET total_billed_amount = total_billed_amount + $2 WHERE id=$1"#,
        )
        .bind(project_id).bind(amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Complete an open project (terminal), returning its FINAL roll-ups. `Ok(None)` = not open.
    ///
    /// ID-only: no company argument. This UPDATE…RETURNING rides the request-dedicated connection, so
    /// RLS fences it to the caller's tenant — another company's project matches 0 rows, which the caller
    /// reports as not-open.
    pub async fn complete(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectCompletionRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE project.projects SET status='completed'::project_status
                   WHERE id=$1 AND status='open'::project_status AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, total_billable_amount, total_costing_amount"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectCompletionRow {
            company_id: r.get("company_id"),
            total_billable_amount: r.get("total_billable_amount"),
            total_costing_amount: r.get("total_costing_amount"),
        }))
    }
}

backbone_core::impl_crud_repository!(ProjectRepository, Project, soft_delete);
