//! Repository for ProjectTemplateTask entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ProjectTemplateTask SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ProjectTemplateTask;

/// Table name for ProjectTemplateTask entities
pub const TABLE_NAME: &str = "project.project_template_tasks";

/// Repository for ProjectTemplateTask entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectTemplateTaskRepository(
    backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectTemplateTaskRepository {
    type Target = backbone_orm::GenericCrudRepository<ProjectTemplateTask, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectTemplateTaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One template task, as materialized into a real task on instantiation.
pub struct TemplateTaskRow {
    pub subject: String,
    pub task_type: Option<String>,
    pub expected_time: Decimal,
}

/// Hand-written ProjectTemplateTask SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl ProjectTemplateTaskRepository {
    /// List a template's tasks in `sequence` order — the order instantiation materializes them in.
    ///
    /// A read outside any transaction; the caller wraps the whole instantiation in
    /// `with_company_scope(Some(company_id))`, so this is fenced (ADR-0008).
    pub async fn list_by_template(
        &self,
        pool: &PgPool,
        template_id: Uuid,
    ) -> Result<Vec<TemplateTaskRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT subject, task_type, expected_time FROM project.project_template_tasks
                   WHERE template_id=$1 AND (metadata->>'deleted_at') IS NULL ORDER BY sequence ASC"#,
            )
            .bind(template_id),
        )
        .await?;
        Ok(rows.iter().map(|r| TemplateTaskRow {
            subject: r.get("subject"), task_type: r.get("task_type"),
            expected_time: r.get("expected_time"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(ProjectTemplateTaskRepository, ProjectTemplateTask, soft_delete);
