//! Repository for ProjectTemplate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ProjectTemplate SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProjectTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ProjectTemplate;

/// Table name for ProjectTemplate entities
pub const TABLE_NAME: &str = "project.project_templates";

/// Repository for ProjectTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectTemplateRepository(
    backbone_orm::GenericCrudRepository<ProjectTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<ProjectTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// What instantiation reads off a template: the project type it stamps out, and whether it may still
/// be used at all.
pub struct TemplateRow {
    pub project_type: String,
    pub is_active: bool,
}

/// Hand-written ProjectTemplate SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl ProjectTemplateRepository {
    /// Read a live template for instantiation. `Ok(None)` = no such template in scope.
    ///
    /// A read outside any transaction; the caller wraps the whole instantiation in
    /// `with_company_scope(Some(company_id))` (the company is on its parameter), so this and every
    /// nested write are fenced (ADR-0008).
    pub async fn find_for_instantiate(
        &self,
        pool: &PgPool,
        template_id: Uuid,
    ) -> Result<Option<TemplateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT project_type::text AS project_type, is_active FROM project.project_templates
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(template_id),
        )
        .await?;
        Ok(row.map(|r| TemplateRow {
            project_type: r.get("project_type"), is_active: r.get("is_active"),
        }))
    }
}

backbone_core::impl_crud_repository!(ProjectTemplateRepository, ProjectTemplate, soft_delete);
