//! Repository for Project entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Project SQL (4-layer rule: services orchestrate, repositories hold
//! the SQL), including the derived financial roll-ups: the cost/billable/billed columns on
//! `project.projects` are refreshed from the converged analytic row (timesheet module's schema)
//! by an explicit verb — they are never live-computed on read.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Project;

/// Table name for Project entities
pub const TABLE_NAME: &str = "project.projects";

/// Repository for Project entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProjectRepository(
    backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProjectRepository {
    type Target = backbone_orm::GenericCrudRepository<Project, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProjectRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a project open writes.
///
/// Mirrors the raw column shape rather than the `Project` entity: `project_type` is cast at the DB
/// (`$4::project_type`) and `status` is hard-coded `open`, so neither is a free parameter.
pub struct NewProjectRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_name: &'a str,
    pub project_type: &'a str,
    pub customer_id: Option<Uuid>,
    pub source_so_id: Option<Uuid>,
    pub currency: &'a str,
}

/// A live project's company + delivery state — what the task path reads before it writes.
pub struct ProjectScopeRow {
    pub company_id: Uuid,
    pub status: String,
}

/// The stored financial triple on `project.projects` — the derived profitability surface.
#[derive(Debug, Clone, PartialEq)]
pub struct ProjectFinancialsRow {
    pub company_id: Uuid,
    pub total_costing_amount: Decimal,
    pub total_billable_amount: Decimal,
    pub total_billed_amount: Decimal,
}

/// The final roll-ups captured as a project completes — what `ProjectCompleted` announces.
pub struct ProjectCompletionRow {
    pub company_id: Uuid,
    pub total_billable_amount: Decimal,
    pub total_costing_amount: Decimal,
}

/// Hand-written Project SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ProjectRepository {
    /// Open a project.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK (a non-request caller has no
    /// ambient scope otherwise).
    pub async fn insert_project(
        &self,
        pool: &PgPool,
        p: &NewProjectRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO project.projects
                     (id, company_id, project_name, project_type, customer_id, source_so_id, currency, status)
                   VALUES ($1,$2,$3,$4::project_type,$5,$6,$7,'open'::project_status)"#,
            )
            .bind(p.id).bind(p.company_id).bind(p.project_name).bind(p.project_type)
            .bind(p.customer_id).bind(p.source_so_id).bind(p.currency),
        )
        .await?;
        Ok(())
    }

    /// Open a project for a confirmed sales order — the per-order mint, at most once.
    ///
    /// The insert lands on the partial unique index `uq_projects_source_so` (one live project per
    /// (company, source sales order)); on conflict it writes nothing and returns `Ok(None)`, and the
    /// caller re-selects the prior project via [`Self::find_id_by_source_so`]. That backstop is what
    /// makes a repeated order confirm mint exactly one project per order — by database, not
    /// bookkeeping.
    ///
    /// Takes the CALLER'S connection so the mint of project + tasks commits as ONE unit. The caller
    /// has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_project_for_so(
        &self,
        conn: &mut sqlx::PgConnection,
        p: &NewProjectRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = sqlx::query(
            r#"INSERT INTO project.projects
                 (id, company_id, project_name, project_type, customer_id, source_so_id, currency, status)
               VALUES ($1,$2,$3,$4::project_type,$5,$6,$7,'open'::project_status)
               ON CONFLICT (company_id, source_so_id)
                 WHERE source_so_id IS NOT NULL AND (metadata->>'deleted_at') IS NULL
               DO NOTHING
               RETURNING id"#,
        )
        .bind(p.id).bind(p.company_id).bind(p.project_name).bind(p.project_type)
        .bind(p.customer_id).bind(p.source_so_id).bind(p.currency)
        .fetch_optional(&mut *conn)
        .await?;
        Ok(row.map(|r| r.get::<uuid::Uuid, _>("id")))
    }

    /// The live project minted for a sales order, if any — the mint's re-select arm.
    ///
    /// Pool read, `fetch_optional_scalar_scoped` (fenced to the caller's company).
    pub async fn find_id_by_source_so(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        source_so_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar::<_, Uuid>(
                r#"SELECT id FROM project.projects
                   WHERE company_id=$1 AND source_so_id=$2
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id)
            .bind(source_so_id),
        )
        .await
    }

    /// Read a live project's company + status — the task path's lookup. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's project is simply not found. The company
    /// comes back on the row so the caller can bind the follow-on INSERT to it explicitly.
    pub async fn find_scope_by_id(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectScopeRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, status::text AS status FROM project.projects
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectScopeRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Write the derived financial triple onto the project — the refresh verb's write arm.
    /// Returns rows affected: 0 = the project is not open, and the caller must roll back.
    ///
    /// Gated on an OPEN project (a completed project's "final" totals stay final — same posture the
    /// retired incremental roll-up carried). Takes the CALLER'S connection so the sums read off the
    /// converged rows and this write settle as ONE unit; the caller has already bound the company.
    pub async fn set_financials_open(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        costing: Decimal,
        billable: Decimal,
        billed: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.projects
               SET total_costing_amount  = $2,
                   total_billable_amount = $3,
                   total_billed_amount   = $4
               WHERE id=$1 AND status='open'::project_status"#,
        )
        .bind(project_id).bind(costing).bind(billable).bind(billed)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Read the stored financial triple — the derived read (no live compute, ever).
    ///
    /// ID-only, fenced as [`Self::find_scope_by_id`]: under HTTP the request-dedicated connection
    /// carries the scope; an event/job caller wraps it in `with_company_scope` or it fails closed.
    pub async fn read_financials(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectFinancialsRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, total_costing_amount, total_billable_amount, total_billed_amount
                   FROM project.projects WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectFinancialsRow {
            company_id: r.get("company_id"),
            total_costing_amount: r.get("total_costing_amount"),
            total_billable_amount: r.get("total_billable_amount"),
            total_billed_amount: r.get("total_billed_amount"),
        }))
    }

    /// Read the project's customer — who a period slice bills to. `Ok(None)` = an internal project
    /// with nobody to bill (the column is nullable).
    ///
    /// ID-only, read outside a tx. Under HTTP the request-dedicated connection carries the scope; an
    /// EVENT/job caller must wrap it in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn find_customer_id(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar::<_, Option<Uuid>>("SELECT customer_id FROM project.projects WHERE id=$1")
                .bind(project_id),
        )
        .await
    }

    /// Read the project's currency — the money context of its rate snapshots, which the billing
    /// exit carries into the Sales Invoice. ID-only, fenced as [`Self::find_customer_id`].
    pub async fn find_currency(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<String, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar::<_, String>("SELECT currency FROM project.projects WHERE id=$1")
                .bind(project_id),
        )
        .await
    }

    /// Roll a billed amount up onto the project's billed total.
    ///
    /// Takes the CALLER'S connection so this and the period's `invoice_id` stamp commit as ONE
    /// unit. The caller has already bound the company on it — don't re-bind here.
    pub async fn add_billed(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        amount: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE project.projects SET total_billed_amount = total_billed_amount + $2 WHERE id=$1"#,
        )
        .bind(project_id).bind(amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Roll a credited amount back off the project's billed total — the reversal's write arm.
    /// Floored at zero so a mis-sized credit can never drive the roll-up negative.
    ///
    /// Takes the CALLER'S connection so this and the `invoice_id` clear commit as ONE unit. The
    /// caller has already bound the company on it — don't re-bind here.
    pub async fn subtract_billed(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
        amount: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE project.projects
               SET total_billed_amount = GREATEST(total_billed_amount - $2, 0) WHERE id=$1"#,
        )
        .bind(project_id).bind(amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Soft-delete a project (stamp `metadata.deleted_at`). Returns rows affected: 0 = not live.
    ///
    /// The delete GUARD (no live converged analytic rows referencing the project) is checked by the
    /// caller before this runs; a database FK cannot cross module schemas, so the service-level
    /// check is the whole enforcement (declared G-PRJ-1 in schema/hooks/convergence_guards.hook.yaml).
    ///
    /// Takes the CALLER'S connection so the guard read and the delete settle as ONE unit.
    pub async fn soft_delete(
        &self,
        conn: &mut sqlx::PgConnection,
        project_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.projects
               SET metadata = jsonb_set(metadata, '{deleted_at}', to_jsonb(NOW()))
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(project_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Complete an open project (terminal), returning its FINAL roll-ups. `Ok(None)` = not open.
    ///
    /// ID-only: no company argument. This UPDATE…RETURNING rides the request-dedicated connection, so
    /// RLS fences it to the caller's tenant — another company's project matches 0 rows, which the caller
    /// reports as not-open.
    pub async fn complete(
        &self,
        pool: &PgPool,
        project_id: Uuid,
    ) -> Result<Option<ProjectCompletionRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE project.projects SET status='completed'::project_status
                   WHERE id=$1 AND status='open'::project_status AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, total_billable_amount, total_costing_amount"#,
            )
            .bind(project_id),
        )
        .await?;
        Ok(row.map(|r| ProjectCompletionRow {
            company_id: r.get("company_id"),
            total_billable_amount: r.get("total_billable_amount"),
            total_costing_amount: r.get("total_costing_amount"),
        }))
    }
}

backbone_core::impl_crud_repository!(ProjectRepository, Project, soft_delete);
