//! Repository for Task entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Task SQL (4-layer rule: services orchestrate, repos hold SQL),
//! including the hybrid status writes (ADR-0016 pattern 3: closed values latch, open/working
//! re-derive from live converged analytic rows) and the per-line service-delivery mint.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::{company_scope, org_scope};

use crate::domain::entity::Task;

/// Table name for Task entities
pub const TABLE_NAME: &str = "project.tasks";

/// Repository for Task entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaskRepository(
    backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaskRepository {
    type Target = backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a task add writes. Mirrors the raw column shape, not the `Task` entity: `status` is
/// hard-coded `open` and `progress` seeded at 0, so neither is a parameter.
pub struct NewTaskRow<'a> {
    pub id: Uuid,
    pub project_id: Uuid,
    pub parent_task_id: Option<Uuid>,
    pub subject: &'a str,
    pub task_type: Option<&'a str>,
    pub expected_time: Decimal,
}

/// Hand-written Task SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl TaskRepository {
    /// Probe that a task belongs to a project — the adjacency-list tree's parent check.
    ///
    /// The scalar read twin lives only in the legacy `company_scope` module (ADR-0029); with no
    /// ambient legacy scope bound it runs as a plain pool read, so the module stays tenant-agnostic.
    pub async fn find_id_in_project(
        &self,
        pool: &PgPool,
        task_id: Uuid,
        project_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT id FROM project.tasks WHERE id=$1 AND project_id=$2")
                .bind(task_id).bind(project_id),
        )
        .await
    }

    /// Read a live task's status. `Ok(None)` = not found. ID-only (ADR-0029): identified by the
    /// id alone.
    pub async fn find_status_by_id(
        &self,
        pool: &PgPool,
        task_id: Uuid,
    ) -> Result<Option<String>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT status::text AS status FROM project.tasks
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(task_id),
        )
        .await?;
        Ok(row.map(|r| r.get::<String, _>("status")))
    }

    /// Add a task to a project.
    ///
    /// A write outside any transaction: takes the pool and runs the tenant-agnostic scoped execute
    /// (request-dedicated connection when the caller bound one, plain pool otherwise).
    pub async fn insert_task(&self, pool: &PgPool, t: &NewTaskRow<'_>) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO project.tasks
                     (id, project_id, parent_task_id, subject, task_type, status, expected_time, progress)
                   VALUES ($1,$2,$3,$4,$5,'open'::task_status,$6,0)"#,
            )
            .bind(t.id).bind(t.project_id).bind(t.parent_task_id).bind(t.subject)
            .bind(t.task_type).bind(t.expected_time),
        )
        .await?;
        Ok(())
    }

    /// Add a task to a project on the CALLER'S connection — the tx-bound twin of
    /// [`Self::insert_task`], used where several writes must commit as ONE unit (template
    /// materialization inside the service-delivery mint). The caller has already relayed any
    /// ambient org scope onto the connection — don't re-bind here.
    pub async fn insert_task_in_tx(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewTaskRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO project.tasks
                 (id, project_id, parent_task_id, subject, task_type, status, expected_time, progress)
               VALUES ($1,$2,$3,$4,$5,'open'::task_status,$6,0)"#,
        )
        .bind(t.id).bind(t.project_id).bind(t.parent_task_id).bind(t.subject)
        .bind(t.task_type).bind(t.expected_time)
        .execute(&mut *conn)
        .await?;
        Ok(())
    }

    /// Mint one task per sales-order line — at most once per line.
    ///
    /// The insert lands on the partial unique index `uq_tasks_origin_sale_line` (one live task per
    /// origin sale line — the origin id is globally unique, so the bare key serves every tenant);
    /// on conflict it writes nothing and returns `Ok(None)`, and the caller re-selects the prior
    /// task via [`Self::find_id_by_origin_sale_line`]. That backstop is what makes a repeated
    /// order confirm mint exactly one task per line — by database, not bookkeeping.
    ///
    /// Takes the CALLER'S connection so the whole service-delivery mint commits as ONE unit. The
    /// caller has already relayed any ambient org scope onto it — don't re-bind here.
    pub async fn insert_task_for_sale_line(
        &self,
        conn: &mut sqlx::PgConnection,
        id: Uuid,
        project_id: Uuid,
        origin_sale_line_id: Uuid,
        subject: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = sqlx::query(
            r#"INSERT INTO project.tasks
                 (id, project_id, subject, status, expected_time, progress, origin_sale_line_id)
               VALUES ($1,$2,$3,'open'::task_status,0,0,$4)
               ON CONFLICT (origin_sale_line_id)
                 WHERE origin_sale_line_id IS NOT NULL AND (metadata->>'deleted_at') IS NULL
               DO NOTHING
               RETURNING id"#,
        )
        .bind(id).bind(project_id).bind(subject).bind(origin_sale_line_id)
        .fetch_optional(&mut *conn)
        .await?;
        Ok(row.map(|r| r.get::<uuid::Uuid, _>("id")))
    }

    /// The live task minted for a sales-order line, if any — the mint's re-select arm.
    ///
    /// Runs on the CALLER'S connection (inside the mint tx).
    pub async fn find_id_by_origin_sale_line(
        &self,
        conn: &mut sqlx::PgConnection,
        origin_sale_line_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT id FROM project.tasks
               WHERE origin_sale_line_id=$1
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(origin_sale_line_id)
        .fetch_optional(&mut *conn)
        .await?;
        Ok(row.map(|r| r.get::<uuid::Uuid, _>("id")))
    }

    /// Write a hand-set status (the hybrid INVERSE) and progress. The LATCH is the value itself:
    /// a closed status (`completed`/`cancelled`) survives every later derivation; an open/working
    /// status is immediately re-derived by the caller (compute acts as the reset guard).
    /// Returns rows affected: 0 = not live — the caller reports not found.
    ///
    /// Takes the CALLER'S connection so a hand-set status and the re-derivation read settle as ONE
    /// unit.
    pub async fn set_status(
        &self,
        conn: &mut sqlx::PgConnection,
        task_id: Uuid,
        status: &str,
        progress: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.tasks SET status=$2::task_status, progress=$3
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(task_id).bind(status).bind(progress)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Derive a task's status (the hybrid FORWARD compute) — skipped for latched tasks. A
    /// non-latched task derives `working` when live converged analytic rows reference it, else
    /// `open`. Returns rows affected: 0 = latched (closed) or gone — nothing was derived.
    ///
    /// The EXISTS probe reads the timesheet module's schema on the SAME connection, so the
    /// derivation and the rows it derives from are consistent within the caller's unit of work.
    pub async fn derive_status(
        &self,
        conn: &mut sqlx::PgConnection,
        task_id: Uuid,
        has_live_rows: bool,
    ) -> Result<u64, sqlx::Error> {
        let derived = if has_live_rows { "working" } else { "open" };
        let done = sqlx::query(
            r#"UPDATE project.tasks SET status=$2::task_status
               WHERE id=$1 AND status IN ('open','working')
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(task_id).bind(derived)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Soft-delete a task (stamp `metadata.deleted_at`). Returns rows affected: 0 = not live.
    ///
    /// The delete GUARD (no live converged analytic rows referencing the task) is checked by the
    /// caller before this runs; a database FK cannot cross module schemas, so the service-level
    /// check is the whole enforcement (declared G-PRJ-2 in schema/hooks/convergence_guards.hook.yaml).
    ///
    /// Takes the CALLER'S connection so the guard read and the delete settle as ONE unit.
    pub async fn soft_delete(
        &self,
        conn: &mut sqlx::PgConnection,
        task_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.tasks
               SET metadata = jsonb_set(metadata, '{deleted_at}', to_jsonb(NOW()))
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(task_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(TaskRepository, Task, soft_delete);
