//! Repository for Task entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Task SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Task;

/// Table name for Task entities
pub const TABLE_NAME: &str = "project.tasks";

/// Repository for Task entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TaskRepository(
    backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TaskRepository {
    type Target = backbone_orm::GenericCrudRepository<Task, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a task add writes. Mirrors the raw column shape, not the `Task` entity: `status` is
/// hard-coded `open` and `progress` seeded at 0, so neither is a parameter.
pub struct NewTaskRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub parent_task_id: Option<Uuid>,
    pub subject: &'a str,
    pub task_type: Option<&'a str>,
    pub expected_time: Decimal,
}

/// Hand-written Task SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl TaskRepository {
    /// Probe that a task belongs to a project — the adjacency-list tree's parent check.
    ///
    /// ID-only: no company argument. `fetch_optional_scalar_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's task is simply not found.
    pub async fn find_id_in_project(
        &self,
        pool: &PgPool,
        task_id: Uuid,
        project_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT id FROM project.tasks WHERE id=$1 AND project_id=$2")
                .bind(task_id).bind(project_id),
        )
        .await
    }

    /// Add a task to a project.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` using the
    /// company it read off the project — that scope is what satisfies the INSERT's WITH CHECK.
    pub async fn insert_task(&self, pool: &PgPool, t: &NewTaskRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO project.tasks
                     (id, company_id, project_id, parent_task_id, subject, task_type, status, expected_time, progress)
                   VALUES ($1,$2,$3,$4,$5,$6,'open'::task_status,$7,0)"#,
            )
            .bind(t.id).bind(t.company_id).bind(t.project_id).bind(t.parent_task_id).bind(t.subject)
            .bind(t.task_type).bind(t.expected_time),
        )
        .await?;
        Ok(())
    }

    /// Move a task's status / progress. Returns rows affected: 0 = not advanceable (open/working only).
    ///
    /// ID-only: no company argument — `execute_scoped` runs it on the request-dedicated connection, so
    /// RLS fences it to the caller's tenant (0 rows otherwise, which the caller's guard already reports
    /// as not-advanceable). `status` is bound as a plain string and cast at the DB (`$2::task_status`),
    /// so a bad value fails as a DB error.
    pub async fn advance(
        &self,
        pool: &PgPool,
        task_id: Uuid,
        status: &str,
        progress: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE project.tasks SET status=$2::task_status, progress=$3
                   WHERE id=$1 AND status IN ('open','working') AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(task_id)
            .bind(status)
            .bind(progress),
        )
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(TaskRepository, Task, soft_delete);
