//! Repository for TimesheetDetail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TimesheetDetail;

/// Table name for TimesheetDetail entities
pub const TABLE_NAME: &str = "project.timesheet_details";

/// Repository for TimesheetDetail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimesheetDetailRepository(
    backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimesheetDetailRepository {
    type Target = backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimesheetDetailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TimesheetDetailRepository, TimesheetDetail, soft_delete);
