//! Repository for Timesheet entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Timesheet SQL — including the transition gates that make a timesheet
//! bill at most once (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Timesheet, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Timesheet;

/// Table name for Timesheet entities
pub const TABLE_NAME: &str = "project.timesheets";

/// Repository for Timesheet entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimesheetRepository(
    backbone_orm::GenericCrudRepository<Timesheet, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimesheetRepository {
    type Target = backbone_orm::GenericCrudRepository<Timesheet, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimesheetRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a time-log writes. Mirrors the raw column shape, not the `Timesheet` entity: `status`
/// is hard-coded `submitted` and the totals are the service's already-computed, money-rounded rolls.
pub struct NewTimesheetRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub employee_id: Option<Uuid>,
    pub currency: &'a str,
    pub total_hours: Decimal,
    pub total_billable_amount: Decimal,
    pub total_costing_amount: Decimal,
}

/// What the cancellation path reads before it reverses.
pub struct TimesheetCancelRow {
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub status: String,
    pub total_billable_amount: Decimal,
    pub total_costing_amount: Decimal,
}

/// What the billing seam reads before it hands off: `invoice_id` is Some only once billed, which is
/// what makes a re-bill return the original invoice instead of cutting a second one.
pub struct TimesheetBillingRow {
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub currency: String,
    pub status: String,
    pub total_billable_amount: Decimal,
    pub invoice_id: Option<Uuid>,
}

/// Hand-written Timesheet SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl TimesheetRepository {
    /// Insert a submitted timesheet header.
    ///
    /// Takes the CALLER'S connection so the header, its lines and the project roll-up commit as ONE
    /// unit. The caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_timesheet(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewTimesheetRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO project.timesheets
                 (id, company_id, project_id, employee_id, currency, status, total_hours,
                  total_billable_amount, total_costing_amount)
               VALUES ($1,$2,$3,$4,$5,'submitted'::timesheet_status,$6,$7,$8)"#,
        )
        .bind(t.id).bind(t.company_id).bind(t.project_id).bind(t.employee_id).bind(t.currency)
        .bind(t.total_hours).bind(t.total_billable_amount).bind(t.total_costing_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a live timesheet for cancellation. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument — it rides a connection carrying the caller's `app.company_id`, so
    /// another company's timesheet is simply not found. The company comes back on the row so the caller
    /// can bind the reversal tx to it explicitly.
    pub async fn find_for_cancel(
        &self,
        pool: &PgPool,
        timesheet_id: Uuid,
    ) -> Result<Option<TimesheetCancelRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, project_id, status::text AS status, total_billable_amount, total_costing_amount
                   FROM project.timesheets WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(timesheet_id),
        )
        .await?;
        Ok(row.map(|r| TimesheetCancelRow {
            company_id: r.get("company_id"), project_id: r.get("project_id"), status: r.get("status"),
            total_billable_amount: r.get("total_billable_amount"),
            total_costing_amount: r.get("total_costing_amount"),
        }))
    }

    /// Claim the `submitted → cancelled` transition exactly once. Returns rows affected: 0 = a racing
    /// caller already cancelled + reversed, so this one must roll back and do nothing.
    ///
    /// Takes the CALLER'S connection so this and the roll-up reversal commit as ONE unit. The caller has
    /// already bound the company on it — don't re-bind here.
    pub async fn mark_cancelled(
        &self,
        conn: &mut sqlx::PgConnection,
        timesheet_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.timesheets SET status='cancelled'::timesheet_status
               WHERE id=$1 AND status='submitted'::timesheet_status"#,
        )
        .bind(timesheet_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Read a live timesheet for the billing seam. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument. Under HTTP the request-dedicated connection carries the scope. When
    /// driven by an EVENT/job, the caller MUST wrap this in `with_company_scope(Some(company_id))` —
    /// otherwise it fails closed.
    pub async fn find_for_billing(
        &self,
        pool: &PgPool,
        timesheet_id: Uuid,
    ) -> Result<Option<TimesheetBillingRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, project_id, currency, status::text AS status, total_billable_amount, invoice_id
                   FROM project.timesheets WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(timesheet_id),
        )
        .await?;
        Ok(row.map(|r| TimesheetBillingRow {
            company_id: r.get("company_id"), project_id: r.get("project_id"),
            currency: r.get("currency"), status: r.get("status"),
            total_billable_amount: r.get("total_billable_amount"), invoice_id: r.get("invoice_id"),
        }))
    }

    /// Claim the `submitted → billed` transition exactly once, recording billing's echoed invoice.
    /// Returns rows affected: 0 = a racing caller already billed it, so this one must roll back and
    /// re-read the original invoice. This gate is what makes a timesheet bill AT MOST once.
    ///
    /// Takes the CALLER'S connection so this and the project's billed roll-up commit as ONE unit. The
    /// caller has already bound the company on it — don't re-bind here.
    pub async fn mark_billed(
        &self,
        conn: &mut sqlx::PgConnection,
        timesheet_id: Uuid,
        invoice_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE project.timesheets SET status='billed'::timesheet_status, invoice_id=$2
               WHERE id=$1 AND status='submitted'::timesheet_status"#,
        )
        .bind(timesheet_id)
        .bind(invoice_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Re-read the invoice the winner recorded, after a lost `mark_billed` race. ID-only, same fencing
    /// as [`Self::find_for_billing`].
    pub async fn fetch_invoice_id(
        &self,
        pool: &PgPool,
        timesheet_id: Uuid,
    ) -> Result<Uuid, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT invoice_id FROM project.timesheets WHERE id=$1")
                .bind(timesheet_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(TimesheetRepository, Timesheet, soft_delete);
