//! Repository for TimesheetDetail entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written TimesheetDetail SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::TimesheetDetail;

/// Table name for TimesheetDetail entities
pub const TABLE_NAME: &str = "project.timesheet_details";

/// Repository for TimesheetDetail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimesheetDetailRepository(
    backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimesheetDetailRepository {
    type Target = backbone_orm::GenericCrudRepository<TimesheetDetail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimesheetDetailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row one timesheet line writes. Mirrors the raw column shape, not the `TimesheetDetail`
/// entity: the rates are the service's already-resolved snapshots (explicit, else the activity type's
/// default) and the amounts its already-computed, money-rounded products.
pub struct NewTimesheetDetailRow<'a> {
    pub id: Uuid,
    pub timesheet_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub description: Option<&'a str>,
    pub hours: Decimal,
    pub billing_rate: Decimal,
    pub costing_rate: Decimal,
    pub is_billable: bool,
    pub billable_amount: Decimal,
    pub costing_amount: Decimal,
}

/// One billable line, as handed to billing to become an invoice line.
pub struct BillableLineRow {
    pub activity_type_id: Option<Uuid>,
    pub description: Option<String>,
    pub hours: Decimal,
    pub billing_rate: Decimal,
}

/// Hand-written TimesheetDetail SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl TimesheetDetailRepository {
    /// Insert one timesheet line.
    ///
    /// Takes the CALLER'S connection so every line, the header and the project roll-up commit as ONE
    /// unit. The caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_detail(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewTimesheetDetailRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO project.timesheet_details
                 (id, timesheet_id, activity_type_id, task_id, description, hours, billing_rate,
                  costing_rate, is_billable, billable_amount, costing_amount)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)"#,
        )
        .bind(l.id).bind(l.timesheet_id).bind(l.activity_type_id).bind(l.task_id).bind(l.description)
        .bind(l.hours).bind(l.billing_rate).bind(l.costing_rate).bind(l.is_billable)
        .bind(l.billable_amount).bind(l.costing_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// List a timesheet's BILLABLE lines — what the billing seam hands off as invoice lines.
    ///
    /// ID-only, read outside a tx. Under HTTP the request-dedicated connection carries the scope; an
    /// EVENT/job caller must wrap it in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn list_billable_lines(
        &self,
        pool: &PgPool,
        timesheet_id: Uuid,
    ) -> Result<Vec<BillableLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT activity_type_id, description, hours, billing_rate
                   FROM project.timesheet_details WHERE timesheet_id=$1 AND is_billable=true"#,
            )
            .bind(timesheet_id),
        )
        .await?;
        Ok(rows.iter().map(|r| BillableLineRow {
            activity_type_id: r.get("activity_type_id"), description: r.get("description"),
            hours: r.get("hours"), billing_rate: r.get("billing_rate"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(TimesheetDetailRepository, TimesheetDetail, soft_delete);
