//! Validator for ActivityType entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ActivityType>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::ActivityType;

/// Validator type alias for ActivityType entities.
pub type ActivityTypeValidator = EntityValidator<ActivityType>;

/// Build a validator for ActivityType with all schema-defined field rules.
pub fn activity_type_validator() -> ActivityTypeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &ActivityType| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
