//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod activity_type_validator;
pub mod project_validator;
pub mod project_template_validator;
pub mod project_template_task_validator;
pub mod task_validator;
pub mod timesheet_validator;
pub mod timesheet_detail_validator;

pub use activity_type_validator::{ActivityTypeValidator, activity_type_validator};
pub use project_validator::{ProjectValidator, project_validator};
pub use project_template_validator::{ProjectTemplateValidator, project_template_validator};
pub use project_template_task_validator::{ProjectTemplateTaskValidator, project_template_task_validator};
pub use task_validator::{TaskValidator, task_validator};
pub use timesheet_validator::{TimesheetValidator, timesheet_validator};
pub use timesheet_detail_validator::{TimesheetDetailValidator, timesheet_detail_validator};

// <<< CUSTOM
// END CUSTOM
