//! Validator for ProjectTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ProjectTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ProjectTemplate;

/// Validator type alias for ProjectTemplate entities.
pub type ProjectTemplateValidator = EntityValidator<ProjectTemplate>;

/// Build a validator for ProjectTemplate with all schema-defined field rules.
pub fn project_template_validator() -> ProjectTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("template_name", |e: &ProjectTemplate| &e.template_name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
