//! Validator for ProjectTemplateTask entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ProjectTemplateTask>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::ProjectTemplateTask;

/// Validator type alias for ProjectTemplateTask entities.
pub type ProjectTemplateTaskValidator = EntityValidator<ProjectTemplateTask>;

/// Build a validator for ProjectTemplateTask with all schema-defined field rules.
pub fn project_template_task_validator() -> ProjectTemplateTaskValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &ProjectTemplateTask| &e.subject))
        .rule(OptionalNotBlank::new("task_type", |e: &ProjectTemplateTask| e.task_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
