//! Validator for Project entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Project>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Project;

/// Validator type alias for Project entities.
pub type ProjectValidator = EntityValidator<Project>;

/// Build a validator for Project with all schema-defined field rules.
pub fn project_validator() -> ProjectValidator {
    EntityValidator::new()
        .rule(RequiredString::new("project_name", |e: &Project| &e.project_name))
        .rule(RequiredString::new("currency", |e: &Project| &e.currency))
        .rule(OptionalNotBlank::new("notes", |e: &Project| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: G-PRJ-1 (implement in CUSTOM zone)
    // hook rule: G-PRJ-2 (implement in CUSTOM zone)
    // hook rule: G-PRJ-3 (implement in CUSTOM zone)
    // hook rule: G-PRJ-4 (implement in CUSTOM zone)
    // hook rule: G-PRJ-5 (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
