//! Validator for Task entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Task>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Task;

/// Validator type alias for Task entities.
pub type TaskValidator = EntityValidator<Task>;

/// Build a validator for Task with all schema-defined field rules.
pub fn task_validator() -> TaskValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &Task| &e.subject))
        .rule(OptionalNotBlank::new("task_type", |e: &Task| e.task_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
