//! Validator for TimesheetDetail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimesheetDetail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::TimesheetDetail;

/// Validator type alias for TimesheetDetail entities.
pub type TimesheetDetailValidator = EntityValidator<TimesheetDetail>;

/// Build a validator for TimesheetDetail with all schema-defined field rules.
pub fn timesheet_detail_validator() -> TimesheetDetailValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("description", |e: &TimesheetDetail| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
