//! Auth configuration for ActivityType handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ActivityType>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ActivityTypeService;
use crate::domain::entity::ActivityType;

/// Permission string constants for ActivityType operations.
pub mod permissions {
    pub const LIST:        &str = "activity_type:list";
    pub const READ:        &str = "activity_type:read";
    pub const CREATE:      &str = "activity_type:create";
    pub const UPDATE:      &str = "activity_type:update";
    pub const DELETE:      &str = "activity_type:delete";
    pub const RESTORE:     &str = "activity_type:restore";
    pub const TRASH:       &str = "activity_type:trash";
    pub const EMPTY_TRASH: &str = "activity_type:empty_trash";
    pub const BULK_CREATE: &str = "activity_type:bulk_create";
    pub const UPSERT:      &str = "activity_type:upsert";
}

/// Resource policy for ActivityType — maps CRUD actions to permission strings.
pub struct ActivityTypePolicy;

#[async_trait]
impl ResourcePolicy<ActivityType> for ActivityTypePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ActivityType,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ActivityType handlers.
///
/// Wraps `ActivityTypeService` and checks `ActivityTypePolicy` before delegating.
pub type ActivityTypeGuard = PermissionGuard<ActivityType>;

/// Service-integrated permission guard for ActivityType (for use in generated handlers).
pub type ActivityTypeServiceGuard = ServicePermissionGuard<ActivityType, ActivityTypeService, ActivityTypePolicy>;

// <<< CUSTOM
// END CUSTOM
