//! Auth configuration for Project handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Project>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ProjectService;
use crate::domain::entity::Project;

/// Permission string constants for Project operations.
pub mod permissions {
    pub const LIST:        &str = "project:list";
    pub const READ:        &str = "project:read";
    pub const CREATE:      &str = "project:create";
    pub const UPDATE:      &str = "project:update";
    pub const DELETE:      &str = "project:delete";
    pub const RESTORE:     &str = "project:restore";
    pub const TRASH:       &str = "project:trash";
    pub const EMPTY_TRASH: &str = "project:empty_trash";
    pub const BULK_CREATE: &str = "project:bulk_create";
    pub const UPSERT:      &str = "project:upsert";
}

/// Resource policy for Project — maps CRUD actions to permission strings.
pub struct ProjectPolicy;

#[async_trait]
impl ResourcePolicy<Project> for ProjectPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Project,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Project handlers.
///
/// Wraps `ProjectService` and checks `ProjectPolicy` before delegating.
pub type ProjectGuard = PermissionGuard<Project>;

/// Service-integrated permission guard for Project (for use in generated handlers).
pub type ProjectServiceGuard = ServicePermissionGuard<Project, ProjectService, ProjectPolicy>;

// <<< CUSTOM
// END CUSTOM
