//! Auth configuration for ProjectTemplate handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ProjectTemplate>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ProjectTemplateService;
use crate::domain::entity::ProjectTemplate;

/// Permission string constants for ProjectTemplate operations.
pub mod permissions {
    pub const LIST:        &str = "project_template:list";
    pub const READ:        &str = "project_template:read";
    pub const CREATE:      &str = "project_template:create";
    pub const UPDATE:      &str = "project_template:update";
    pub const DELETE:      &str = "project_template:delete";
    pub const RESTORE:     &str = "project_template:restore";
    pub const TRASH:       &str = "project_template:trash";
    pub const EMPTY_TRASH: &str = "project_template:empty_trash";
    pub const BULK_CREATE: &str = "project_template:bulk_create";
    pub const UPSERT:      &str = "project_template:upsert";
}

/// Resource policy for ProjectTemplate — maps CRUD actions to permission strings.
pub struct ProjectTemplatePolicy;

#[async_trait]
impl ResourcePolicy<ProjectTemplate> for ProjectTemplatePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ProjectTemplate,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ProjectTemplate handlers.
///
/// Wraps `ProjectTemplateService` and checks `ProjectTemplatePolicy` before delegating.
pub type ProjectTemplateGuard = PermissionGuard<ProjectTemplate>;

/// Service-integrated permission guard for ProjectTemplate (for use in generated handlers).
pub type ProjectTemplateServiceGuard = ServicePermissionGuard<ProjectTemplate, ProjectTemplateService, ProjectTemplatePolicy>;

// <<< CUSTOM
// END CUSTOM
