//! Auth configuration for ProjectTemplateTask handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ProjectTemplateTask>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ProjectTemplateTaskService;
use crate::domain::entity::ProjectTemplateTask;

/// Permission string constants for ProjectTemplateTask operations.
pub mod permissions {
    pub const LIST:        &str = "project_template_task:list";
    pub const READ:        &str = "project_template_task:read";
    pub const CREATE:      &str = "project_template_task:create";
    pub const UPDATE:      &str = "project_template_task:update";
    pub const DELETE:      &str = "project_template_task:delete";
    pub const RESTORE:     &str = "project_template_task:restore";
    pub const TRASH:       &str = "project_template_task:trash";
    pub const EMPTY_TRASH: &str = "project_template_task:empty_trash";
    pub const BULK_CREATE: &str = "project_template_task:bulk_create";
    pub const UPSERT:      &str = "project_template_task:upsert";
}

/// Resource policy for ProjectTemplateTask — maps CRUD actions to permission strings.
pub struct ProjectTemplateTaskPolicy;

#[async_trait]
impl ResourcePolicy<ProjectTemplateTask> for ProjectTemplateTaskPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ProjectTemplateTask,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ProjectTemplateTask handlers.
///
/// Wraps `ProjectTemplateTaskService` and checks `ProjectTemplateTaskPolicy` before delegating.
pub type ProjectTemplateTaskGuard = PermissionGuard<ProjectTemplateTask>;

/// Service-integrated permission guard for ProjectTemplateTask (for use in generated handlers).
pub type ProjectTemplateTaskServiceGuard = ServicePermissionGuard<ProjectTemplateTask, ProjectTemplateTaskService, ProjectTemplateTaskPolicy>;

// <<< CUSTOM
// END CUSTOM
