//! Auth configuration for Task handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Task>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TaskService;
use crate::domain::entity::Task;

/// Permission string constants for Task operations.
pub mod permissions {
    pub const LIST:        &str = "task:list";
    pub const READ:        &str = "task:read";
    pub const CREATE:      &str = "task:create";
    pub const UPDATE:      &str = "task:update";
    pub const DELETE:      &str = "task:delete";
    pub const RESTORE:     &str = "task:restore";
    pub const TRASH:       &str = "task:trash";
    pub const EMPTY_TRASH: &str = "task:empty_trash";
    pub const BULK_CREATE: &str = "task:bulk_create";
    pub const UPSERT:      &str = "task:upsert";
}

/// Resource policy for Task — maps CRUD actions to permission strings.
pub struct TaskPolicy;

#[async_trait]
impl ResourcePolicy<Task> for TaskPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Task,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Task handlers.
///
/// Wraps `TaskService` and checks `TaskPolicy` before delegating.
pub type TaskGuard = PermissionGuard<Task>;

/// Service-integrated permission guard for Task (for use in generated handlers).
pub type TaskServiceGuard = ServicePermissionGuard<Task, TaskService, TaskPolicy>;

// <<< CUSTOM
// END CUSTOM
