//! Auth configuration for TimesheetDetail handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TimesheetDetail>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimesheetDetailService;
use crate::domain::entity::TimesheetDetail;

/// Permission string constants for TimesheetDetail operations.
pub mod permissions {
    pub const LIST:        &str = "timesheet_detail:list";
    pub const READ:        &str = "timesheet_detail:read";
    pub const CREATE:      &str = "timesheet_detail:create";
    pub const UPDATE:      &str = "timesheet_detail:update";
    pub const DELETE:      &str = "timesheet_detail:delete";
    pub const RESTORE:     &str = "timesheet_detail:restore";
    pub const TRASH:       &str = "timesheet_detail:trash";
    pub const EMPTY_TRASH: &str = "timesheet_detail:empty_trash";
    pub const BULK_CREATE: &str = "timesheet_detail:bulk_create";
    pub const UPSERT:      &str = "timesheet_detail:upsert";
}

/// Resource policy for TimesheetDetail — maps CRUD actions to permission strings.
pub struct TimesheetDetailPolicy;

#[async_trait]
impl ResourcePolicy<TimesheetDetail> for TimesheetDetailPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TimesheetDetail,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TimesheetDetail handlers.
///
/// Wraps `TimesheetDetailService` and checks `TimesheetDetailPolicy` before delegating.
pub type TimesheetDetailGuard = PermissionGuard<TimesheetDetail>;

/// Service-integrated permission guard for TimesheetDetail (for use in generated handlers).
pub type TimesheetDetailServiceGuard = ServicePermissionGuard<TimesheetDetail, TimesheetDetailService, TimesheetDetailPolicy>;

// <<< CUSTOM
// END CUSTOM
