//! ActivityType API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ActivityType CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ACTIVITYTYPE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ActivityType
pub struct ActivityTypeTestData;

impl TestDataGenerator for ActivityTypeTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "billing_rate": 0,
            "costing_rate": 0,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "billing_rate": 0,
            "costing_rate": 0,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ACTIVITYTYPE API TEST
// ============================================================================

/// ActivityType API test suite
pub struct ActivityTypeApiTest {
    inner: GenericCrudTest<ActivityTypeTestData>,
}

impl ActivityTypeApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/activity_types", "ActivityType");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ActivityTypeTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ActivityTypeApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_activity_type_crud() {
        let mut test = ActivityTypeApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ActivityType specific tests here
// <<< CUSTOM TESTS END >>>
