//! Project API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Project CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROJECT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Project
pub struct ProjectTestData;

impl TestDataGenerator for ProjectTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "project_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "project_type": "external",
            "customer_id": null,
            "source_so_id": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "open",
            "expected_start_date": null,
            "expected_end_date": null,
            "total_costing_amount": 0,
            "total_billable_amount": 0,
            "total_billed_amount": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "project_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "project_type": "external",
            "customer_id": null,
            "source_so_id": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "open",
            "expected_start_date": null,
            "expected_end_date": null,
            "total_costing_amount": 0,
            "total_billable_amount": 0,
            "total_billed_amount": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PROJECT API TEST
// ============================================================================

/// Project API test suite
pub struct ProjectApiTest {
    inner: GenericCrudTest<ProjectTestData>,
}

impl ProjectApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/projects", "Project");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ProjectTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ProjectApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_project_crud() {
        let mut test = ProjectApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Project specific tests here
// <<< CUSTOM TESTS END >>>
