//! ProjectTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ProjectTemplate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROJECTTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ProjectTemplate
pub struct ProjectTemplateTestData;

impl TestDataGenerator for ProjectTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "template_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "project_type": "external",
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "template_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "project_type": "external",
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PROJECTTEMPLATE API TEST
// ============================================================================

/// ProjectTemplate API test suite
pub struct ProjectTemplateApiTest {
    inner: GenericCrudTest<ProjectTemplateTestData>,
}

impl ProjectTemplateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/project_templates", "ProjectTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ProjectTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ProjectTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_project_template_crud() {
        let mut test = ProjectTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ProjectTemplate specific tests here
// <<< CUSTOM TESTS END >>>
