//! ProjectTemplateTask API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ProjectTemplateTask CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROJECTTEMPLATETASK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ProjectTemplateTask
pub struct ProjectTemplateTaskTestData;

impl TestDataGenerator for ProjectTemplateTaskTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "template_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "task_type": null,
            "expected_time": 0,
            "sequence": 1,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "template_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "task_type": null,
            "expected_time": 0,
            "sequence": 1,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/project_templates", &super::project_template_api_test::ProjectTemplateTestData).await {
            deps.push(("template_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// PROJECTTEMPLATETASK API TEST
// ============================================================================

/// ProjectTemplateTask API test suite
pub struct ProjectTemplateTaskApiTest {
    inner: GenericCrudTest<ProjectTemplateTaskTestData>,
}

impl ProjectTemplateTaskApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/project_template_tasks", "ProjectTemplateTask");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ProjectTemplateTaskTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ProjectTemplateTaskApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_project_template_task_crud() {
        let mut test = ProjectTemplateTaskApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ProjectTemplateTask specific tests here
// <<< CUSTOM TESTS END >>>
