//! Project Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ActivityTypeService;
use crate::application::service::ProjectService;
use crate::application::service::ProjectTemplateService;
use crate::application::service::ProjectTemplateTaskService;
use crate::application::service::TaskService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ActivityType service
    pub activity_type_service: Arc<ActivityTypeService>,
    /// Project service
    pub project_service: Arc<ProjectService>,
    /// ProjectTemplate service
    pub project_template_service: Arc<ProjectTemplateService>,
    /// ProjectTemplateTask service
    pub project_template_task_service: Arc<ProjectTemplateTaskService>,
    /// Task service
    pub task_service: Arc<TaskService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        activity_type_service: Arc<ActivityTypeService>,
        project_service: Arc<ProjectService>,
        project_template_service: Arc<ProjectTemplateService>,
        project_template_task_service: Arc<ProjectTemplateTaskService>,
        task_service: Arc<TaskService>
    ) -> Self {
        Self {
            activity_type_service,
            project_service,
            project_template_service,
            project_template_task_service,
            task_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::ProjectModule) -> Self {
        Self {
            activity_type_service: module.activity_type_service.clone(),
            project_service: module.project_service.clone(),
            project_template_service: module.project_template_service.clone(),
            project_template_task_service: module.project_template_task_service.clone(),
            task_service: module.task_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    activity_type_service: Option<Arc<ActivityTypeService>>,
    project_service: Option<Arc<ProjectService>>,
    project_template_service: Option<Arc<ProjectTemplateService>>,
    project_template_task_service: Option<Arc<ProjectTemplateTaskService>>,
    task_service: Option<Arc<TaskService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ActivityType service.
    pub fn with_activity_type_service(mut self, service: Arc<ActivityTypeService>) -> Self {
        self.activity_type_service = Some(service);
        self
    }

    /// Set the Project service.
    pub fn with_project_service(mut self, service: Arc<ProjectService>) -> Self {
        self.project_service = Some(service);
        self
    }

    /// Set the ProjectTemplate service.
    pub fn with_project_template_service(mut self, service: Arc<ProjectTemplateService>) -> Self {
        self.project_template_service = Some(service);
        self
    }

    /// Set the ProjectTemplateTask service.
    pub fn with_project_template_task_service(mut self, service: Arc<ProjectTemplateTaskService>) -> Self {
        self.project_template_task_service = Some(service);
        self
    }

    /// Set the Task service.
    pub fn with_task_service(mut self, service: Arc<TaskService>) -> Self {
        self.task_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            activity_type_service: self.activity_type_service.expect("activity_type_service is required"),
            project_service: self.project_service.expect("project_service is required"),
            project_template_service: self.project_template_service.expect("project_template_service is required"),
            project_template_task_service: self.project_template_task_service.expect("project_template_task_service is required"),
            task_service: self.task_service.expect("task_service is required"),
        }
    }
}
