//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    activity_type_handler::create_activity_type_routes,
    project_handler::create_project_routes,
    project_template_handler::create_project_template_routes,
    project_template_task_handler::create_project_template_task_routes,
    task_handler::create_task_routes,
};

use crate::application::service::{
    ActivityTypeService,
    ProjectService,
    ProjectTemplateService,
    ProjectTemplateTaskService,
    TaskService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub activity_type: Arc<ActivityTypeService>,
    pub project: Arc<ProjectService>,
    pub project_template: Arc<ProjectTemplateService>,
    pub project_template_task: Arc<ProjectTemplateTaskService>,
    pub task: Arc<TaskService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // ActivityType routes (12 Backbone endpoints)
        .merge(create_activity_type_routes(services.activity_type))
        // Project routes (12 Backbone endpoints)
        .merge(create_project_routes(services.project))
        // ProjectTemplate routes (12 Backbone endpoints)
        .merge(create_project_template_routes(services.project_template))
        // ProjectTemplateTask routes (12 Backbone endpoints)
        .merge(create_project_template_task_routes(services.project_template_task))
        // Task routes (12 Backbone endpoints)
        .merge(create_task_routes(services.task))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn activity_type_routes(service: Arc<ActivityTypeService>) -> Router {
        create_activity_type_routes(service)
    }

    pub fn project_routes(service: Arc<ProjectService>) -> Router {
        create_project_routes(service)
    }

    pub fn project_template_routes(service: Arc<ProjectTemplateService>) -> Router {
        create_project_template_routes(service)
    }

    pub fn project_template_task_routes(service: Arc<ProjectTemplateTaskService>) -> Router {
        create_project_template_task_routes(service)
    }

    pub fn task_routes(service: Arc<TaskService>) -> Router {
        create_task_routes(service)
    }

}
