//! Public events for Project module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ACTIVITYTYPE EVENTS
// ============================================================================

/// Event published when a ActivityType is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeCreatedEvent {
    pub id: ActivityTypeId,
    pub data: ActivityTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ActivityType is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeUpdatedEvent {
    pub id: ActivityTypeId,
    pub data: ActivityTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ActivityType is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeDeletedEvent {
    pub id: ActivityTypeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROJECT EVENTS
// ============================================================================

/// Event published when a Project is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectCreatedEvent {
    pub id: ProjectId,
    pub data: ProjectDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Project is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectUpdatedEvent {
    pub id: ProjectId,
    pub data: ProjectDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Project is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectDeletedEvent {
    pub id: ProjectId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROJECTTEMPLATE EVENTS
// ============================================================================

/// Event published when a ProjectTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateCreatedEvent {
    pub id: ProjectTemplateId,
    pub data: ProjectTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProjectTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateUpdatedEvent {
    pub id: ProjectTemplateId,
    pub data: ProjectTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProjectTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateDeletedEvent {
    pub id: ProjectTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROJECTTEMPLATETASK EVENTS
// ============================================================================

/// Event published when a ProjectTemplateTask is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskCreatedEvent {
    pub id: ProjectTemplateTaskId,
    pub data: ProjectTemplateTaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProjectTemplateTask is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskUpdatedEvent {
    pub id: ProjectTemplateTaskId,
    pub data: ProjectTemplateTaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProjectTemplateTask is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskDeletedEvent {
    pub id: ProjectTemplateTaskId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TASK EVENTS
// ============================================================================

/// Event published when a Task is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskCreatedEvent {
    pub id: TaskId,
    pub data: TaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Task is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskUpdatedEvent {
    pub id: TaskId,
    pub data: TaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Task is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskDeletedEvent {
    pub id: TaskId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Project module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ProjectEvent {
    ActivityTypeCreated(ActivityTypeCreatedEvent),
    ActivityTypeUpdated(ActivityTypeUpdatedEvent),
    ActivityTypeDeleted(ActivityTypeDeletedEvent),
    ProjectCreated(ProjectCreatedEvent),
    ProjectUpdated(ProjectUpdatedEvent),
    ProjectDeleted(ProjectDeletedEvent),
    ProjectTemplateCreated(ProjectTemplateCreatedEvent),
    ProjectTemplateUpdated(ProjectTemplateUpdatedEvent),
    ProjectTemplateDeleted(ProjectTemplateDeletedEvent),
    ProjectTemplateTaskCreated(ProjectTemplateTaskCreatedEvent),
    ProjectTemplateTaskUpdated(ProjectTemplateTaskUpdatedEvent),
    ProjectTemplateTaskDeleted(ProjectTemplateTaskDeletedEvent),
    TaskCreated(TaskCreatedEvent),
    TaskUpdated(TaskUpdatedEvent),
    TaskDeleted(TaskDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for ProjectEventMetadata {
    fn default() -> Self {
        Self {
            module: "project",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
