//! Project Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Project exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use project::exports::{ActivityTypeDto, ProjectQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ActivityTypeDto` - Data transfer object for ActivityType
/// - `ActivityTypeSummary` - Summary view of ActivityType
/// - `ActivityTypeId` - Type-safe ID wrapper
/// - `ProjectDto` - Data transfer object for Project
/// - `ProjectSummary` - Summary view of Project
/// - `ProjectId` - Type-safe ID wrapper
/// - `ProjectTemplateDto` - Data transfer object for ProjectTemplate
/// - `ProjectTemplateSummary` - Summary view of ProjectTemplate
/// - `ProjectTemplateId` - Type-safe ID wrapper
/// - `ProjectTemplateTaskDto` - Data transfer object for ProjectTemplateTask
/// - `ProjectTemplateTaskSummary` - Summary view of ProjectTemplateTask
/// - `ProjectTemplateTaskId` - Type-safe ID wrapper
/// - `TaskDto` - Data transfer object for Task
/// - `TaskSummary` - Summary view of Task
/// - `TaskId` - Type-safe ID wrapper
/// - `TimesheetDto` - Data transfer object for Timesheet
/// - `TimesheetSummary` - Summary view of Timesheet
/// - `TimesheetId` - Type-safe ID wrapper
/// - `TimesheetDetailDto` - Data transfer object for TimesheetDetail
/// - `TimesheetDetailSummary` - Summary view of TimesheetDetail
/// - `TimesheetDetailId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `ProjectQueryService` - Read-only queries
///
/// ## Public Events
/// - `ActivityTypeCreatedEvent` - Published when ActivityType is created
/// - `ActivityTypeUpdatedEvent` - Published when ActivityType is updated
/// - `ActivityTypeDeletedEvent` - Published when ActivityType is deleted
/// - `ProjectCreatedEvent` - Published when Project is created
/// - `ProjectUpdatedEvent` - Published when Project is updated
/// - `ProjectDeletedEvent` - Published when Project is deleted
/// - `ProjectTemplateCreatedEvent` - Published when ProjectTemplate is created
/// - `ProjectTemplateUpdatedEvent` - Published when ProjectTemplate is updated
/// - `ProjectTemplateDeletedEvent` - Published when ProjectTemplate is deleted
/// - `ProjectTemplateTaskCreatedEvent` - Published when ProjectTemplateTask is created
/// - `ProjectTemplateTaskUpdatedEvent` - Published when ProjectTemplateTask is updated
/// - `ProjectTemplateTaskDeletedEvent` - Published when ProjectTemplateTask is deleted
/// - `TaskCreatedEvent` - Published when Task is created
/// - `TaskUpdatedEvent` - Published when Task is updated
/// - `TaskDeletedEvent` - Published when Task is deleted
/// - `TimesheetCreatedEvent` - Published when Timesheet is created
/// - `TimesheetUpdatedEvent` - Published when Timesheet is updated
/// - `TimesheetDeletedEvent` - Published when Timesheet is deleted
/// - `TimesheetDetailCreatedEvent` - Published when TimesheetDetail is created
/// - `TimesheetDetailUpdatedEvent` - Published when TimesheetDetail is updated
/// - `TimesheetDetailDeletedEvent` - Published when TimesheetDetail is deleted
pub struct ExportSummary;
