//! Public services for Project module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Project module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait ProjectQueryService: Send + Sync {
    /// Get ActivityType by ID
    async fn get_activity_type(&self, id: ActivityTypeId) -> Result<Option<ActivityTypeDto>>;

    /// Get ActivityType summary by ID
    async fn get_activity_type_summary(&self, id: ActivityTypeId) -> Result<Option<ActivityTypeSummary>>;

    /// Check if ActivityType exists
    async fn activity_type_exists(&self, id: ActivityTypeId) -> Result<bool>;

    /// Get Project by ID
    async fn get_project(&self, id: ProjectId) -> Result<Option<ProjectDto>>;

    /// Get Project summary by ID
    async fn get_project_summary(&self, id: ProjectId) -> Result<Option<ProjectSummary>>;

    /// Check if Project exists
    async fn project_exists(&self, id: ProjectId) -> Result<bool>;

    /// Get ProjectTemplate by ID
    async fn get_project_template(&self, id: ProjectTemplateId) -> Result<Option<ProjectTemplateDto>>;

    /// Get ProjectTemplate summary by ID
    async fn get_project_template_summary(&self, id: ProjectTemplateId) -> Result<Option<ProjectTemplateSummary>>;

    /// Check if ProjectTemplate exists
    async fn project_template_exists(&self, id: ProjectTemplateId) -> Result<bool>;

    /// Get ProjectTemplateTask by ID
    async fn get_project_template_task(&self, id: ProjectTemplateTaskId) -> Result<Option<ProjectTemplateTaskDto>>;

    /// Get ProjectTemplateTask summary by ID
    async fn get_project_template_task_summary(&self, id: ProjectTemplateTaskId) -> Result<Option<ProjectTemplateTaskSummary>>;

    /// Check if ProjectTemplateTask exists
    async fn project_template_task_exists(&self, id: ProjectTemplateTaskId) -> Result<bool>;

    /// Get Task by ID
    async fn get_task(&self, id: TaskId) -> Result<Option<TaskDto>>;

    /// Get Task summary by ID
    async fn get_task_summary(&self, id: TaskId) -> Result<Option<TaskSummary>>;

    /// Check if Task exists
    async fn task_exists(&self, id: TaskId) -> Result<bool>;

    /// Get Timesheet by ID
    async fn get_timesheet(&self, id: TimesheetId) -> Result<Option<TimesheetDto>>;

    /// Get Timesheet summary by ID
    async fn get_timesheet_summary(&self, id: TimesheetId) -> Result<Option<TimesheetSummary>>;

    /// Check if Timesheet exists
    async fn timesheet_exists(&self, id: TimesheetId) -> Result<bool>;

    /// Get TimesheetDetail by ID
    async fn get_timesheet_detail(&self, id: TimesheetDetailId) -> Result<Option<TimesheetDetailDto>>;

    /// Get TimesheetDetail summary by ID
    async fn get_timesheet_detail_summary(&self, id: TimesheetDetailId) -> Result<Option<TimesheetDetailSummary>>;

    /// Check if TimesheetDetail exists
    async fn timesheet_detail_exists(&self, id: TimesheetDetailId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of ProjectQueryService
pub struct ProjectQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> ProjectQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
