//! Public types for Project module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// ACTIVITYTYPE TYPES
// ============================================================================

/// Type-safe ID for ActivityType
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ActivityTypeId(pub Uuid);

impl ActivityTypeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ActivityTypeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ActivityTypeId> for Uuid {
    fn from(id: ActivityTypeId) -> Self {
        id.0
    }
}

/// Data transfer object for ActivityType
///
/// This is the public representation of ActivityType for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeDto {
    pub id: ActivityTypeId,
    pub company_id: Uuid,
    pub name: String,
    pub billing_rate: Decimal,
    pub costing_rate: Decimal,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of ActivityType for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeSummary {
    pub id: ActivityTypeId,
    pub name: String,
}

/// Reference to ActivityType for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityTypeRef {
    pub id: ActivityTypeId,
}

// ============================================================================
// PROJECT TYPES
// ============================================================================

/// Type-safe ID for Project
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProjectId(pub Uuid);

impl ProjectId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProjectId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProjectId> for Uuid {
    fn from(id: ProjectId) -> Self {
        id.0
    }
}

/// Data transfer object for Project
///
/// This is the public representation of Project for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectDto {
    pub id: ProjectId,
    pub company_id: Uuid,
    pub project_name: String,
    pub project_type: ProjectType,
    pub customer_id: Option<Uuid>,
    pub source_so_id: Option<Uuid>,
    pub currency: String,
    pub status: ProjectStatus,
    pub expected_start_date: Option<DateTime<Utc>>,
    pub expected_end_date: Option<DateTime<Utc>>,
    pub total_costing_amount: Decimal,
    pub total_billable_amount: Decimal,
    pub total_billed_amount: Decimal,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Project for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSummary {
    pub id: ProjectId,
    pub project_name: String,
    pub status: ProjectStatus,
}

/// Reference to Project for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectRef {
    pub id: ProjectId,
}

// ============================================================================
// PROJECTTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for ProjectTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProjectTemplateId(pub Uuid);

impl ProjectTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProjectTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProjectTemplateId> for Uuid {
    fn from(id: ProjectTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for ProjectTemplate
///
/// This is the public representation of ProjectTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateDto {
    pub id: ProjectTemplateId,
    pub company_id: Uuid,
    pub template_name: String,
    pub project_type: ProjectType,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of ProjectTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateSummary {
    pub id: ProjectTemplateId,
    pub template_name: String,
}

/// Reference to ProjectTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateRef {
    pub id: ProjectTemplateId,
}

// ============================================================================
// PROJECTTEMPLATETASK TYPES
// ============================================================================

/// Type-safe ID for ProjectTemplateTask
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProjectTemplateTaskId(pub Uuid);

impl ProjectTemplateTaskId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProjectTemplateTaskId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProjectTemplateTaskId> for Uuid {
    fn from(id: ProjectTemplateTaskId) -> Self {
        id.0
    }
}

/// Data transfer object for ProjectTemplateTask
///
/// This is the public representation of ProjectTemplateTask for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskDto {
    pub id: ProjectTemplateTaskId,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub subject: String,
    pub task_type: Option<String>,
    pub expected_time: Decimal,
    pub sequence: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of ProjectTemplateTask for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskSummary {
    pub id: ProjectTemplateTaskId,
}

/// Reference to ProjectTemplateTask for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectTemplateTaskRef {
    pub id: ProjectTemplateTaskId,
}

// ============================================================================
// TASK TYPES
// ============================================================================

/// Type-safe ID for Task
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaskId(pub Uuid);

impl TaskId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TaskId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TaskId> for Uuid {
    fn from(id: TaskId) -> Self {
        id.0
    }
}

/// Data transfer object for Task
///
/// This is the public representation of Task for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskDto {
    pub id: TaskId,
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub parent_task_id: Option<Uuid>,
    pub subject: String,
    pub task_type: Option<String>,
    pub status: TaskStatus,
    pub expected_time: Decimal,
    pub progress: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of Task for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskSummary {
    pub id: TaskId,
    pub status: TaskStatus,
}

/// Reference to Task for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskRef {
    pub id: TaskId,
}

// ============================================================================
// TIMESHEET TYPES
// ============================================================================

/// Type-safe ID for Timesheet
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimesheetId(pub Uuid);

impl TimesheetId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimesheetId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimesheetId> for Uuid {
    fn from(id: TimesheetId) -> Self {
        id.0
    }
}

/// Data transfer object for Timesheet
///
/// This is the public representation of Timesheet for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetDto {
    pub id: TimesheetId,
    pub company_id: Uuid,
    pub project_id: Uuid,
    pub employee_id: Option<Uuid>,
    pub currency: String,
    pub status: TimesheetStatus,
    pub total_hours: Decimal,
    pub total_billable_amount: Decimal,
    pub total_costing_amount: Decimal,
    pub invoice_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Timesheet for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetSummary {
    pub id: TimesheetId,
    pub status: TimesheetStatus,
}

/// Reference to Timesheet for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetRef {
    pub id: TimesheetId,
}

// ============================================================================
// TIMESHEETDETAIL TYPES
// ============================================================================

/// Type-safe ID for TimesheetDetail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimesheetDetailId(pub Uuid);

impl TimesheetDetailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TimesheetDetailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TimesheetDetailId> for Uuid {
    fn from(id: TimesheetDetailId) -> Self {
        id.0
    }
}

/// Data transfer object for TimesheetDetail
///
/// This is the public representation of TimesheetDetail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetDetailDto {
    pub id: TimesheetDetailId,
    pub company_id: Uuid,
    pub timesheet_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub description: Option<String>,
    pub hours: Decimal,
    pub billing_rate: Decimal,
    pub costing_rate: Decimal,
    pub is_billable: bool,
    pub billable_amount: Decimal,
    pub costing_amount: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of TimesheetDetail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetDetailSummary {
    pub id: TimesheetDetailId,
}

/// Reference to TimesheetDetail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetDetailRef {
    pub id: TimesheetDetailId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
