//! Project Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ActivityTypeService;
pub use application::service::ProjectService;
pub use application::service::ProjectTemplateService;
pub use application::service::ProjectTemplateTaskService;
pub use application::service::TaskService;

// Re-exports - Validation
pub use application::validator::{ValidationError, ValidationResult};

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Project module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let project = ProjectModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = project.all_crud_routes();
/// ```
pub struct ProjectModule {
    pub(crate) activity_type_service: Arc<ActivityTypeService>,
    pub(crate) project_service: Arc<ProjectService>,
    pub(crate) project_template_service: Arc<ProjectTemplateService>,
    pub(crate) project_template_task_service: Arc<ProjectTemplateTaskService>,
    pub(crate) task_service: Arc<TaskService>,
    // <<< CUSTOM FIELDS
    /// Inbound read-port for sibling modules (`use project::exports::ProjectQueryService`).
    /// `pub` (not `pub(crate)`) so siblings can obtain the trait object — clone the Arc
    /// to hold `Arc<dyn ProjectQueryService>`. Lives in the CUSTOM FIELDS block (regen-safe).
    pub query_service: std::sync::Arc<dyn crate::exports::ProjectQueryService>,
    /// The validated write surface (project/task lifecycle, hybrid task status, the billing
    /// exit, the confirm-mint, guarded deletes, the derived financial reads). Composing hosts
    /// drive this; the generic-CRUD services above remain the trusted/admin escape hatch.
    pub write_service: std::sync::Arc<crate::application::service::ProjectWriteService>,
    // END CUSTOM
}

impl ProjectModule {
    /// Create a new module builder
    pub fn builder() -> ProjectModuleBuilder {
        ProjectModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_activity_type_routes,
            create_project_routes,
            create_project_template_routes,
            create_project_template_task_routes,
            create_task_routes,
        };

        Router::new()
            .merge(create_activity_type_routes(self.activity_type_service.clone()))
            .merge(create_project_routes(self.project_service.clone()))
            .merge(create_project_template_routes(self.project_template_service.clone()))
            .merge(create_project_template_task_routes(self.project_template_task_service.clone()))
            .merge(create_task_routes(self.task_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_activity_type_read_routes,
            create_project_read_routes,
            create_project_template_read_routes,
            create_project_template_task_read_routes,
            create_task_read_routes,
        };

        Router::new()
            .merge(create_activity_type_read_routes(self.activity_type_service.clone()))
            .merge(create_project_read_routes(self.project_service.clone()))
            .merge(create_project_template_read_routes(self.project_template_service.clone()))
            .merge(create_project_template_task_read_routes(self.project_template_task_service.clone()))
            .merge(create_task_read_routes(self.task_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for ProjectModule
pub struct ProjectModuleBuilder {
    db_pool: Option<PgPool>,
}

impl ProjectModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<ProjectModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // ActivityType service
        let activity_type_repository = Arc::new(ActivityTypeRepository::new(db_pool.clone()));
        let activity_type_service = Arc::new(ActivityTypeService::with_repository(activity_type_repository.clone()));

        // Project service
        let project_repository = Arc::new(ProjectRepository::new(db_pool.clone()));
        let project_service = Arc::new(ProjectService::with_repository(project_repository.clone()));

        // ProjectTemplate service
        let project_template_repository = Arc::new(ProjectTemplateRepository::new(db_pool.clone()));
        let project_template_service = Arc::new(ProjectTemplateService::with_repository(project_template_repository.clone()));

        // ProjectTemplateTask service
        let project_template_task_repository = Arc::new(ProjectTemplateTaskRepository::new(db_pool.clone()));
        let project_template_task_service = Arc::new(ProjectTemplateTaskService::with_repository(project_template_task_repository.clone()));

        // Task service
        let task_repository = Arc::new(TaskRepository::new(db_pool.clone()));
        let task_service = Arc::new(TaskService::with_repository(task_repository.clone()));

        // <<< CUSTOM
        let query_service: std::sync::Arc<dyn crate::exports::ProjectQueryService> =
            std::sync::Arc::new(crate::exports::ProjectQueryServiceImpl::new(
                activity_type_service.clone(),
                project_service.clone(),
                project_template_service.clone(),
                project_template_task_service.clone(),
                task_service.clone(),
            ));
        let write_service = std::sync::Arc::new(
            crate::application::service::ProjectWriteService::new(db_pool.clone()),
        );
        // END CUSTOM

        Ok(ProjectModule {
            activity_type_service,
            project_service,
            project_template_service,
            project_template_task_service,
            task_service,
            // <<< CUSTOM
            query_service,
            write_service,
            // END CUSTOM
        })
    }
}

impl Default for ProjectModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
