//! Use case type aliases for ActivityType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateActivityTypeDto, UpdateActivityTypeDto};
use crate::application::service::ActivityTypeService;
use crate::domain::entity::ActivityType;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateActivityTypeUseCase = CreateUseCase<ActivityType, CreateActivityTypeDto, ActivityTypeService>;
pub type UpdateActivityTypeUseCase = UpdateUseCase<ActivityType, UpdateActivityTypeDto, ActivityTypeService>;
pub type GetActivityTypeUseCase    = GetUseCase<ActivityType, ActivityTypeService>;
pub type DeleteActivityTypeUseCase = DeleteUseCase<ActivityType, ActivityTypeService>;
pub type ListActivityTypeUseCase   = ListUseCase<ActivityType, ActivityTypeService>;

// <<< CUSTOM
// END CUSTOM
