//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod activity_type_usecases;
pub mod project_usecases;
pub mod project_template_usecases;
pub mod project_template_task_usecases;
pub mod task_usecases;
pub mod timesheet_usecases;
pub mod timesheet_detail_usecases;

pub use activity_type_usecases::{
    CreateActivityTypeUseCase, UpdateActivityTypeUseCase, GetActivityTypeUseCase,
    DeleteActivityTypeUseCase, ListActivityTypeUseCase,
};
pub use project_usecases::{
    CreateProjectUseCase, UpdateProjectUseCase, GetProjectUseCase,
    DeleteProjectUseCase, ListProjectUseCase,
};
pub use project_template_usecases::{
    CreateProjectTemplateUseCase, UpdateProjectTemplateUseCase, GetProjectTemplateUseCase,
    DeleteProjectTemplateUseCase, ListProjectTemplateUseCase,
};
pub use project_template_task_usecases::{
    CreateProjectTemplateTaskUseCase, UpdateProjectTemplateTaskUseCase, GetProjectTemplateTaskUseCase,
    DeleteProjectTemplateTaskUseCase, ListProjectTemplateTaskUseCase,
};
pub use task_usecases::{
    CreateTaskUseCase, UpdateTaskUseCase, GetTaskUseCase,
    DeleteTaskUseCase, ListTaskUseCase,
};
pub use timesheet_usecases::{
    CreateTimesheetUseCase, UpdateTimesheetUseCase, GetTimesheetUseCase,
    DeleteTimesheetUseCase, ListTimesheetUseCase,
};
pub use timesheet_detail_usecases::{
    CreateTimesheetDetailUseCase, UpdateTimesheetDetailUseCase, GetTimesheetDetailUseCase,
    DeleteTimesheetDetailUseCase, ListTimesheetDetailUseCase,
};

// <<< CUSTOM
// END CUSTOM
