//! Use case type aliases for ProjectTemplateTask aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateProjectTemplateTaskDto, UpdateProjectTemplateTaskDto};
use crate::application::service::ProjectTemplateTaskService;
use crate::domain::entity::ProjectTemplateTask;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateProjectTemplateTaskUseCase = CreateUseCase<ProjectTemplateTask, CreateProjectTemplateTaskDto, ProjectTemplateTaskService>;
pub type UpdateProjectTemplateTaskUseCase = UpdateUseCase<ProjectTemplateTask, UpdateProjectTemplateTaskDto, ProjectTemplateTaskService>;
pub type GetProjectTemplateTaskUseCase    = GetUseCase<ProjectTemplateTask, ProjectTemplateTaskService>;
pub type DeleteProjectTemplateTaskUseCase = DeleteUseCase<ProjectTemplateTask, ProjectTemplateTaskService>;
pub type ListProjectTemplateTaskUseCase   = ListUseCase<ProjectTemplateTask, ProjectTemplateTaskService>;

// <<< CUSTOM
// END CUSTOM
