//! Use case type aliases for ProjectTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateProjectTemplateDto, UpdateProjectTemplateDto};
use crate::application::service::ProjectTemplateService;
use crate::domain::entity::ProjectTemplate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateProjectTemplateUseCase = CreateUseCase<ProjectTemplate, CreateProjectTemplateDto, ProjectTemplateService>;
pub type UpdateProjectTemplateUseCase = UpdateUseCase<ProjectTemplate, UpdateProjectTemplateDto, ProjectTemplateService>;
pub type GetProjectTemplateUseCase    = GetUseCase<ProjectTemplate, ProjectTemplateService>;
pub type DeleteProjectTemplateUseCase = DeleteUseCase<ProjectTemplate, ProjectTemplateService>;
pub type ListProjectTemplateUseCase   = ListUseCase<ProjectTemplate, ProjectTemplateService>;

// <<< CUSTOM
// END CUSTOM
