//! Use case type aliases for Project aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateProjectDto, UpdateProjectDto};
use crate::application::service::ProjectService;
use crate::domain::entity::Project;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateProjectUseCase = CreateUseCase<Project, CreateProjectDto, ProjectService>;
pub type UpdateProjectUseCase = UpdateUseCase<Project, UpdateProjectDto, ProjectService>;
pub type GetProjectUseCase    = GetUseCase<Project, ProjectService>;
pub type DeleteProjectUseCase = DeleteUseCase<Project, ProjectService>;
pub type ListProjectUseCase   = ListUseCase<Project, ProjectService>;

// <<< CUSTOM
// END CUSTOM
