//! Use case type aliases for Task aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTaskDto, UpdateTaskDto};
use crate::application::service::TaskService;
use crate::domain::entity::Task;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTaskUseCase = CreateUseCase<Task, CreateTaskDto, TaskService>;
pub type UpdateTaskUseCase = UpdateUseCase<Task, UpdateTaskDto, TaskService>;
pub type GetTaskUseCase    = GetUseCase<Task, TaskService>;
pub type DeleteTaskUseCase = DeleteUseCase<Task, TaskService>;
pub type ListTaskUseCase   = ListUseCase<Task, TaskService>;

// <<< CUSTOM
// END CUSTOM
