//! Use case type aliases for TimesheetDetail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimesheetDetailDto, UpdateTimesheetDetailDto};
use crate::application::service::TimesheetDetailService;
use crate::domain::entity::TimesheetDetail;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimesheetDetailUseCase = CreateUseCase<TimesheetDetail, CreateTimesheetDetailDto, TimesheetDetailService>;
pub type UpdateTimesheetDetailUseCase = UpdateUseCase<TimesheetDetail, UpdateTimesheetDetailDto, TimesheetDetailService>;
pub type GetTimesheetDetailUseCase    = GetUseCase<TimesheetDetail, TimesheetDetailService>;
pub type DeleteTimesheetDetailUseCase = DeleteUseCase<TimesheetDetail, TimesheetDetailService>;
pub type ListTimesheetDetailUseCase   = ListUseCase<TimesheetDetail, TimesheetDetailService>;

// <<< CUSTOM
// END CUSTOM
